import { AudioEngine } from './audio-engine.js';
import { NOTE_NAMES, SCALE_INTERVALS, pitchInfo } from './pitch-detection.js';
import { renderFxRack } from './fx-rack.js';
import { PRESETS, applyPreset, serializePreset } from './presets.js';
import { renderWav, downloadBlob } from './export.js';
import { setupNavigation } from './ui-navigation.js';
import { PitchEditor } from './editor.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={noteNames:NOTE_NAMES,key:'C',scale:'Major',customScale:null,manualTarget:'Auto',currentPreset:'Natural Pop Vocal',inputGain:1,retuneSpeed:35,correctionAmount:80,humanize:30,flexTune:20,transitionSmoothing:55,snapScale:true,hardTune:false,naturalTune:true,wetDry:85,formantPreserve:true,formantShift:0,genderTone:0,throatLength:0,voiceCharacter:45,naturalness:75,mixerDryWet:85,mixerVolume:100,mixerPan:0,mixerSend:35,outputGain:95,latencyMode:'interactive',fx:{},favorites:{}};
const engine=new AudioEngine(state);let editor,waveDrag=null,metroTimer=null,lastFrame=performance.now();
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function setStatus(msg){$('#audioStatus').textContent=msg;toast(msg)}
async function withAudio(fn){try{await engine.init();await engine.ctx.resume();return await fn()}catch(e){setStatus(e.message||'Audio error')}}
function bindControls(){ $$('input[type=range]').forEach(el=>{const apply=()=>{state[el.id]=Number(el.value);const sp=$(`[data-value-for="${el.id}"]`);if(sp)sp.textContent=Number(el.value).toFixed(el.step&&el.step!=='1'?1:0);engine.update();drawAll()};el.addEventListener('input',apply);apply()}); ['snapScale','hardTune','naturalTune','formantPreserve','performanceMode','mobileMode'].forEach(id=>{$('#'+id)?.addEventListener('change',e=>{state[id]=e.target.checked;if(id==='hardTune'&&state.hardTune)$('#naturalTune').checked=state.naturalTune=false;engine.update()})}); $('#latencyMode').addEventListener('change',e=>state.latencyMode=e.target.value);$('#themeToggle').onclick=()=>document.body.classList.toggle('light');$('#resetApp').onclick=()=>{localStorage.removeItem('vocaltune-state');location.reload()}}
function buildScaleUI(){const key=$('#keySelect'),scale=$('#scaleSelect'),target=$('#targetNote');NOTE_NAMES.forEach(n=>{key.add(new Option(n,n));target.add(new Option(n,n))});target.add(new Option('Auto','Auto',true,true));Object.keys(SCALE_INTERVALS).forEach(s=>scale.add(new Option(s,s)));key.value=state.key;scale.value=state.scale;key.onchange=()=>{state.key=key.value;state.customScale=null;updateScale()};scale.onchange=()=>{state.scale=scale.value;state.customScale=null;updateScale()};target.onchange=()=>state.manualTarget=target.value;updateScale()}
function updateScale(){const allowed=(state.customScale||SCALE_INTERVALS[state.scale].map(i=>(NOTE_NAMES.indexOf(state.key)+i)%12));$('#noteToggles').innerHTML='';NOTE_NAMES.forEach((n,i)=>{const b=document.createElement('button');b.className='note-toggle '+(allowed.includes(i)?'active':'');b.textContent=n;b.onclick=()=>{state.customScale=state.customScale||[...allowed];state.customScale=state.customScale.includes(i)?state.customScale.filter(x=>x!==i):[...state.customScale,i].sort((a,b)=>a-b);updateScale()};$('#noteToggles').append(b)});$('#keyboard').innerHTML='';NOTE_NAMES.concat(NOTE_NAMES).forEach((n,i)=>{const k=document.createElement('div');k.className=`key ${n.includes('#')?'black':''} ${allowed.includes(i%12)?'allowed':''}`;k.textContent=n;$('#keyboard').append(k)});$('#scaleSummary').textContent=`${state.key} ${state.scale}: ${allowed.map(i=>NOTE_NAMES[i]).join(', ')}`;$('#dashKeyScale').textContent=`${state.key} ${state.scale}`;$('#saveScale').onclick=()=>{localStorage.setItem('vocaltune-custom-scale',JSON.stringify(state.customScale||allowed));toast('Custom scale saved locally')}}
function buildPresets(){const custom=JSON.parse(localStorage.getItem('vocaltune-presets')||'[]'),all=[...PRESETS,...custom];$('#presetList').innerHTML='';all.forEach((p,i)=>{const row=document.createElement('div');row.className='preset-item';row.innerHTML=`<div><strong>${p.name}</strong><br><small>${p.category}</small></div><div><button class="fav">${state.favorites[p.name]?'★':'☆'}</button><button>Load</button></div>`;row.querySelector('.fav').onclick=()=>{state.favorites[p.name]=!state.favorites[p.name];buildPresets()};row.querySelectorAll('button')[1].onclick=()=>{applyPreset(state,p);syncControls();toast(`Loaded ${p.name}`)};$('#presetList').append(row)})}
function syncControls(){Object.entries(state).forEach(([k,v])=>{const el=$('#'+k);if(!el)return;if(el.type==='checkbox')el.checked=!!v;else el.value=v});$('#dashPreset').textContent=state.currentPreset;updateScale();renderFxRack($('#fxRack'),state,()=>engine.update());engine.update();drawAll()}
function bindTransport(){['playBtn','globalPlay'].forEach(id=>$('#'+id).onclick=()=>withAudio(()=>engine.play()));['stopBtn','globalStop'].forEach(id=>$('#'+id).onclick=()=>engine.stop());$('#pauseBtn').onclick=()=>engine.pause();['recordBtn','globalRecord','quickRecord'].forEach(id=>$('#'+id).onclick=()=>withAudio(async()=>{if(engine.mediaRecorder?.state==='recording'){engine.stopRecording();$('#recordBtn').textContent='● Start Recording'}else{await engine.startRecording();$('#recordBtn').textContent='■ Stop Recording'}}));$('#monitorBtn').onclick=()=>withAudio(async()=>{await engine.toggleMonitor(!state.monitoring);$('#monitorBtn').textContent=state.monitoring?'Monitoring On':'Monitoring Off'});$('#metronomeBtn').onclick=()=>toggleMetronome();$('#trimBtn').onclick=()=>engine.trim();$('#cutBtn').onclick=()=>engine.cut();$('#splitBtn').onclick=()=>engine.split()}
function bindImport(){const load=f=>withAudio(()=>engine.loadFile(f));$('#audioFile').onchange=e=>e.target.files[0]&&load(e.target.files[0]);$('#quickImport').onclick=()=>$('#quickImportFile').click();$('#quickImportFile').onchange=e=>e.target.files[0]&&load(e.target.files[0]);const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&load(e.dataTransfer.files[0]))}
function bindWaveform(){const c=$('#waveformCanvas');c.addEventListener('pointerdown',e=>{waveDrag=timeFromCanvas(e,c);engine.cursor=waveDrag;engine.pausedAt=waveDrag});c.addEventListener('pointermove',e=>{if(waveDrag!=null)engine.setSelection(waveDrag,timeFromCanvas(e,c))});addEventListener('pointerup',()=>waveDrag=null)}
function timeFromCanvas(e,c){const r=c.getBoundingClientRect();return Math.max(0,Math.min(engine.duration(),(e.clientX-r.left)/r.width*engine.duration()))}
function drawWaveform(){const c=$('#waveformCanvas'),x=c.getContext('2d'),r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;x.fillStyle='#05070d';x.fillRect(0,0,c.width,c.height);const b=engine.buffer;if(!b)return;const data=b.getChannelData(0),step=Math.ceil(data.length/c.width),mid=c.height/2;x.strokeStyle='#20d6b5';x.beginPath();for(let i=0;i<c.width;i++){let min=1,max=-1;for(let j=0;j<step;j++){const v=data[i*step+j]||0;min=Math.min(min,v);max=Math.max(max,v)}x.moveTo(i,mid+min*mid*.9);x.lineTo(i,mid+max*mid*.9)}x.stroke();const sel=engine.selection;if(sel.end>sel.start){x.fillStyle='rgba(124,92,255,.25)';x.fillRect(sel.start/engine.duration()*c.width,0,(sel.end-sel.start)/engine.duration()*c.width,c.height)}x.fillStyle='#ff4d6d';x.fillRect(engine.time()/engine.duration()*c.width,0,2*devicePixelRatio,c.height)}
function drawMeters(){const data=new Uint8Array(engine.mixer?.analyser.frequencyBinCount||1024);engine.mixer?.analyser.getByteTimeDomainData(data);let sum=0,peak=0;for(const v of data){const s=(v-128)/128;sum+=s*s;peak=Math.max(peak,Math.abs(s))}const rms=Math.sqrt(sum/data.length),db=rms?20*Math.log10(rms):-Infinity,pdb=peak?20*Math.log10(peak):-Infinity;['inputMeter','outputMeter','stereoMeter'].forEach(id=>drawMeter($('#'+id),db));$('#inputDb').textContent=fmtDb(db);$('#outputDb').textContent=fmtDb(db);$('#rmsMeter').textContent=fmtDb(db);$('#peakMeter').textContent=fmtDb(pdb);$('#lufsMeter').textContent=(db-3).toFixed(1)+' LUFS';$('#phaseMeter').textContent=(1-Math.min(1,rms)).toFixed(2);document.documentElement.style.setProperty('--cpu',`${Math.min(90,Math.round((performance.now()-lastFrame)*3))}%`);$('#cpuValue').textContent=Math.min(90,Math.round((performance.now()-lastFrame)*3))+'%';lastFrame=performance.now()}
function drawMeter(c,db){const r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;const x=c.getContext('2d'),p=Math.max(0,Math.min(1,(db+60)/60));x.fillStyle='#05070d';x.fillRect(0,0,c.width,c.height);const g=x.createLinearGradient(0,0,c.width,0);g.addColorStop(0,'#20d6b5');g.addColorStop(.75,'#f7b955');g.addColorStop(1,'#ff4d6d');x.fillStyle=g;x.fillRect(0,0,c.width*p,c.height)}
function fmtDb(v){return isFinite(v)?v.toFixed(1)+' dB':'-∞ dB'}
function drawAnalyzers(){const a=engine.mixer?.analyser;if(!a)return;const spec=$('#spectrumCanvas'),scope=$('#scopeCanvas');[spec,scope].forEach(c=>{const r=c.getBoundingClientRect();c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio});let s=new Uint8Array(a.frequencyBinCount);a.getByteFrequencyData(s);let x=spec.getContext('2d');x.fillStyle='#05070d';x.fillRect(0,0,spec.width,spec.height);x.fillStyle='#7c5cff';s.forEach((v,i)=>x.fillRect(i/s.length*spec.width,spec.height-v/255*spec.height,spec.width/s.length+1,v/255*spec.height));a.getByteTimeDomainData(s);x=scope.getContext('2d');x.fillStyle='#05070d';x.fillRect(0,0,scope.width,scope.height);x.strokeStyle='#20d6b5';x.beginPath();s.forEach((v,i)=>{const y=v/255*scope.height,xx=i/s.length*scope.width;i?x.lineTo(xx,y):x.moveTo(xx,y)});x.stroke()}
function drawAll(){drawWaveform();drawMeters();drawAnalyzers();editor?.draw()}
function loop(){const p=engine.analyzePitch();$('#noteDisplay').textContent=p.note||'--';$('#freqDisplay').textContent=p.frequency?p.frequency.toFixed(1)+' Hz':'-- Hz';$('#centsDisplay').textContent=(p.cents??0)+' cents';$('#confidenceDisplay').textContent=Math.round((p.confidence||0)*100)+'%';$('#pitchMonitor').textContent=p.target||'--';$('#timeReadout').textContent=formatTime(engine.time());drawAll();requestAnimationFrame(loop)}
function formatTime(t){const m=Math.floor(t/60),s=(t%60).toFixed(3).padStart(6,'0');return `${m}:${s}`}
function toggleMetronome(){if(metroTimer){clearInterval(metroTimer);metroTimer=null;$('#metronomeBtn').textContent='Metronome Off';return}withAudio(()=>{const tick=()=>{const o=engine.ctx.createOscillator(),g=engine.ctx.createGain();o.frequency.value=1200;g.gain.setValueAtTime(.12,engine.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,engine.ctx.currentTime+.06);o.connect(g).connect(engine.ctx.destination);o.start();o.stop(engine.ctx.currentTime+.07)};tick();metroTimer=setInterval(tick,60000/Number($('#bpm').value));$('#metronomeBtn').textContent='Metronome On'})}
function bindEditor(){editor=new PitchEditor($('#pitchEditorCanvas'),engine,state);$('#detectNotesBtn').onclick=()=>editor.detect();$('#zoomInBtn').onclick=()=>{editor.zoom=Math.min(8,editor.zoom*1.5);editor.draw()};$('#zoomOutBtn').onclick=()=>{editor.zoom=Math.max(1,editor.zoom/1.5);editor.draw()};$('#undoBtn').onclick=()=>editor.undo();$('#redoBtn').onclick=()=>editor.redo();$('#splitNoteBtn').onclick=()=>editor.split();$('#mergeNoteBtn').onclick=()=>editor.merge()}
function bindExports(){async function exp(mode,name){try{$('#exportStatus').textContent='Rendering...';const blob=await renderWav(engine.buffer,state,mode);downloadBlob(blob,name);$('#exportStatus').textContent='Export complete.'}catch(e){$('#exportStatus').textContent=e.message}}$('#exportWet').onclick=()=>exp('wet','vocaltune-processed.wav');$('#exportDry').onclick=()=>exp('dry','vocaltune-dry.wav');$('#exportWetOnly').onclick=()=>exp('wet','vocaltune-wet.wav');$('#exportProject').onclick=()=>downloadBlob(new Blob([JSON.stringify({state,notes:editor.notes},null,2)],{type:'application/json'}),'vocaltune-project.json');$('#importProjectBtn').onclick=()=>$('#importProject').click();$('#importProject').onchange=async e=>{const f=e.target.files[0];if(!f)return;Object.assign(state,JSON.parse(await f.text()).state);syncControls()};$('#exportPreset').onclick=()=>downloadBlob(new Blob([JSON.stringify(serializePreset(state,$('#presetName').value),null,2)],{type:'application/json'}),'vocaltune-preset.json');$('#exportPresetPack').onclick=()=>downloadBlob(new Blob([JSON.stringify(PRESETS,null,2)],{type:'application/json'}),'vocaltune-preset-pack.json');$('#savePreset').onclick=()=>{const arr=JSON.parse(localStorage.getItem('vocaltune-presets')||'[]');arr.push(serializePreset(state,$('#presetName').value));localStorage.setItem('vocaltune-presets',JSON.stringify(arr));buildPresets();$('#presetStatus').textContent='Preset saved locally.'};$('#importPreset').onchange=async e=>{const p=JSON.parse(await e.target.files[0].text());const arr=JSON.parse(localStorage.getItem('vocaltune-presets')||'[]');arr.push(p);localStorage.setItem('vocaltune-presets',JSON.stringify(arr));buildPresets()}}
function keyboard(){addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.code==='Space'){e.preventDefault();engine.playing?engine.pause():withAudio(()=>engine.play())}if(e.key.toLowerCase()==='s')engine.stop();if(e.key.toLowerCase()==='r')$('#recordBtn').click();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?editor.redo():editor.undo()}})}
engine.addEventListener('status',e=>setStatus(e.detail));engine.addEventListener('buffer',()=>{$('#fileInfo').textContent=engine.fileName?`${engine.fileName} • ${engine.duration().toFixed(2)}s`:'No file loaded.';drawWaveform()});
setupNavigation();bindControls();buildScaleUI();bindTransport();bindImport();bindWaveform();bindEditor();bindExports();keyboard();renderFxRack($('#fxRack'),state,()=>engine.update());buildPresets();syncControls();loop();
