import { detectPitchYin, pitchInfo } from './pitch-detection.js';
import { PitchCorrectionEngine } from './pitch-correction.js';
import { FormantEngine } from './formant-engine.js';
import { FxRack } from './fx-rack.js';
import { Mixer } from './mixer.js';
export class AudioEngine extends EventTarget{
  constructor(state){super();this.state=state;this.ctx=null;this.buffer=null;this.source=null;this.mediaRecorder=null;this.recordChunks=[];this.playing=false;this.startedAt=0;this.pausedAt=0;this.selection={start:0,end:0};this.cursor=0;this.pitcher=new PitchCorrectionEngine(state)}
  async init(){if(this.ctx)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)({latencyHint:this.state.latencyMode||'interactive'});this.inputGain=this.ctx.createGain();this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=2048;this.formant=new FormantEngine(this.ctx);this.fx=new FxRack(this.ctx);this.mixer=new Mixer(this.ctx);this.workletNode=null;if(location.protocol!=='file:'&&this.ctx.audioWorklet){await this.ctx.audioWorklet.addModule('js/audio-worklet-processor.js');this.workletNode=new AudioWorkletNode(this.ctx,'vocal-tune-processor');this.inputGain.connect(this.workletNode).connect(this.formant.input)}else{this.inputGain.connect(this.formant.input)}this.inputGain.connect(this.analyser);this.formant.output.connect(this.fx.input);this.fx.output.connect(this.mixer.input);this.update();this.dispatch('status','Audio ready')}
  update(){if(!this.ctx)return;this.inputGain.gain.value=this.state.inputGain??1;this.formant.update(this.state);this.fx.update(this.state);this.mixer.update(this.state);if(this.workletNode){this.workletNode.parameters.get('wet').value=(this.state.wetDry??85)/100}}
  async ensureMic(){await this.init();const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});this.micStream=stream;this.micSource?.disconnect();this.micSource=this.ctx.createMediaStreamSource(stream);this.micSource.connect(this.inputGain);this.dispatch('status','Microphone connected');return stream}
  async toggleMonitor(on){if(on){await this.ensureMic();this.state.monitoring=true}else{this.state.monitoring=false;this.micSource?.disconnect()}this.dispatch('status',this.state.monitoring?'Monitoring on':'Monitoring off')}
  async startRecording(){const stream=await this.ensureMic();this.recordChunks=[];this.mediaRecorder=new MediaRecorder(stream);this.mediaRecorder.ondataavailable=e=>{if(e.data.size)this.recordChunks.push(e.data)};this.mediaRecorder.onstop=async()=>{const blob=new Blob(this.recordChunks,{type:this.mediaRecorder.mimeType});await this.loadBlob(blob,'Recording.webm')};this.mediaRecorder.start();this.dispatch('status','Recording...')}
  stopRecording(){if(this.mediaRecorder?.state==='recording'){this.mediaRecorder.stop();this.dispatch('status','Recording stopped')}}
  async loadFile(file){await this.loadBlob(file,file.name)}
  async loadBlob(blob,name='Audio'){await this.init();const arr=await blob.arrayBuffer();this.buffer=await this.ctx.decodeAudioData(arr.slice(0));this.fileName=name;this.pausedAt=0;this.cursor=0;this.dispatch('buffer',this.buffer);this.dispatch('status',`Loaded ${name}`)}
  play(){if(!this.buffer)return this.dispatch('status','Load audio first');this.stop(false);this.source=this.ctx.createBufferSource();this.source.buffer=this.buffer;this.source.connect(this.inputGain);this.source.onended=()=>{this.playing=false;this.dispatch('status','Playback ended')};this.startedAt=this.ctx.currentTime-this.pausedAt;this.source.start(0,this.pausedAt);this.playing=true;this.dispatch('status','Playing')}
  pause(){if(!this.playing)return;this.pausedAt=Math.min(this.duration(),this.ctx.currentTime-this.startedAt);this.stop(false);this.dispatch('status','Paused')}
  stop(reset=true){if(this.source){this.source.onended=null;this.source.stop();this.source.disconnect();this.source=null}this.playing=false;if(reset)this.pausedAt=0;this.dispatch('status',reset?'Stopped':'Paused')}
  duration(){return this.buffer?this.buffer.duration:0}
  time(){return this.playing?Math.min(this.duration(),this.ctx.currentTime-this.startedAt):this.pausedAt}
  setSelection(a,b){this.selection={start:Math.max(0,Math.min(a,b)),end:Math.min(this.duration(),Math.max(a,b))};this.cursor=this.selection.start;this.dispatch('buffer',this.buffer)}
  trim(){const {start,end}=this.selection;if(!this.buffer||end<=start)return this.dispatch('status','Select a waveform range first');this.buffer=this.sliceBuffer(start,end);this.pausedAt=0;this.dispatch('buffer',this.buffer);this.dispatch('status','Trimmed selection')}
  cut(){const {start,end}=this.selection;if(!this.buffer||end<=start)return this.dispatch('status','Select a waveform range first');const before=this.sliceBuffer(0,start),after=this.sliceBuffer(end,this.duration());this.buffer=this.concatBuffers([before,after]);this.pausedAt=0;this.dispatch('buffer',this.buffer);this.dispatch('status','Cut selection')}
  split(){if(!this.buffer)return;this.dispatch('status',`Split marker placed at ${this.cursor.toFixed(2)}s`)}
  sliceBuffer(start,end){const sr=this.buffer.sampleRate,len=Math.max(1,Math.floor((end-start)*sr)),out=this.ctx.createBuffer(this.buffer.numberOfChannels,len,sr);for(let ch=0;ch<out.numberOfChannels;ch++)out.copyToChannel(this.buffer.getChannelData(ch).slice(Math.floor(start*sr),Math.floor(end*sr)),ch);return out}
  concatBuffers(parts){const sr=this.buffer.sampleRate,len=parts.reduce((a,b)=>a+b.length,0),out=this.ctx.createBuffer(this.buffer.numberOfChannels,len,sr);for(let ch=0;ch<out.numberOfChannels;ch++){let off=0;for(const p of parts){out.copyToChannel(p.getChannelData(Math.min(ch,p.numberOfChannels-1)),ch,off);off+=p.length}}return out}
  analyzePitch(){if(!this.buffer)return {frequency:0,confidence:0};const t=this.time(),sr=this.buffer.sampleRate,size=2048,start=Math.max(0,Math.floor(t*sr)-size/2),data=this.buffer.getChannelData(0).slice(start,start+size);const det=detectPitchYin(data,sr);const info=pitchInfo(det.frequency,this.state);const ratio=this.pitcher.computeRatio(det.frequency);if(this.workletNode)this.workletNode.parameters.get('pitchRatio').value=ratio;return {...det,...info,ratio}}
  dispatch(type,detail){this.dispatchEvent(new CustomEvent(type,{detail}))}
}
