import { detectPitchYin, frequencyToMidi, midiToFrequency, midiToNote } from './pitch-detection.js';
export class PitchEditor{
  constructor(canvas,engine,state){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.engine=engine;this.state=state;this.notes=[];this.pitchCurve=[];this.zoom=1;this.history=[];this.future=[];this.selected=null;this.drag=null;this.bind();this.resize();addEventListener('resize',()=>this.resize())}
  resize(){const r=this.canvas.getBoundingClientRect();this.canvas.width=r.width*devicePixelRatio;this.canvas.height=r.height*devicePixelRatio;this.draw()}
  snapshot(){this.history.push(JSON.stringify(this.notes));this.future=[]}
  undo(){if(!this.history.length)return;this.future.push(JSON.stringify(this.notes));this.notes=JSON.parse(this.history.pop());this.draw()}
  redo(){if(!this.future.length)return;this.history.push(JSON.stringify(this.notes));this.notes=JSON.parse(this.future.pop());this.draw()}
  detect(){const b=this.engine.buffer;if(!b)return;this.snapshot();this.notes=[];this.pitchCurve=[];const sr=b.sampleRate,ch=b.getChannelData(0),win=2048,hop=1024;let current=null;for(let pos=0;pos+win<ch.length;pos+=hop){const det=detectPitchYin(ch.slice(pos,pos+win),sr);if(det.frequency&&det.confidence>.45){const time=pos/sr,midi=Math.round(frequencyToMidi(det.frequency));this.pitchCurve.push({time,midi:frequencyToMidi(det.frequency),conf:det.confidence});if(!current||Math.abs(current.midi-midi)>1||time-current.end>.18){if(current)this.notes.push(current);current={start:time,end:time+hop/sr,midi,conf:det.confidence}}else{current.end=time+hop/sr;current.conf=(current.conf+det.confidence)/2}}}if(current)this.notes.push(current);this.draw()}
  split(){if(this.selected==null)return;this.snapshot();const n=this.notes[this.selected],mid=(n.start+n.end)/2;this.notes.splice(this.selected,1,{...n,end:mid},{...n,start:mid});this.draw()}
  merge(){const idxs=this.notes.map((n,i)=>n.sel?i:null).filter(i=>i!=null);if(idxs.length<2)return;this.snapshot();const selected=idxs.map(i=>this.notes[i]);const merged={start:Math.min(...selected.map(n=>n.start)),end:Math.max(...selected.map(n=>n.end)),midi:Math.round(selected.reduce((a,n)=>a+n.midi,0)/selected.length),conf:selected.reduce((a,n)=>a+n.conf,0)/selected.length};this.notes=this.notes.filter((_,i)=>!idxs.includes(i));this.notes.push(merged);this.notes.sort((a,b)=>a.start-b.start);this.draw()}
  bind(){this.canvas.addEventListener('pointerdown',e=>{const p=this.point(e);const hit=this.hit(p);if(hit!=null){this.snapshot();this.selected=hit;this.notes[hit].sel=!e.shiftKey||!this.notes[hit].sel;this.drag={i:hit,p,n:{...this.notes[hit]}}}else{this.selected=null;this.notes.forEach(n=>n.sel=false)}this.draw()});this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const p=this.point(e),d=this.toDomain(p),d0=this.toDomain(this.drag.p),n=this.notes[this.drag.i];n.midi=Math.max(36,Math.min(96,Math.round(this.drag.n.midi-(d.midi-d0.midi))));const dt=d.time-d0.time;n.start=Math.max(0,this.drag.n.start+dt);n.end=Math.max(n.start+.05,this.drag.n.end+dt);this.draw()});addEventListener('pointerup',()=>this.drag=null)}
  point(e){const r=this.canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*devicePixelRatio,y:(e.clientY-r.top)*devicePixelRatio}}
  dur(){return Math.max(1,this.engine.duration())/this.zoom}
  toDomain(p){const w=this.canvas.width,h=this.canvas.height;return {time:p.x/w*this.dur(),midi:96-p.y/h*48}}
  hit(p){for(let i=this.notes.length-1;i>=0;i--){const r=this.rect(this.notes[i]);if(p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h)return i}return null}
  rect(n){const w=this.canvas.width,h=this.canvas.height,d=this.dur();return {x:n.start/d*w,w:Math.max(8,(n.end-n.start)/d*w),y:(96-n.midi)/48*h-10*devicePixelRatio,h:20*devicePixelRatio}}
  draw(){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.clearRect(0,0,w,h);c.fillStyle='#05070d';c.fillRect(0,0,w,h);c.strokeStyle='#1d2840';c.lineWidth=1;for(let i=36;i<=96;i++){const y=(96-i)/48*h;if(i%12===0){c.strokeStyle='#34415f';c.fillStyle='#6f7b99';c.fillText(midiToNote(i),8,y-3)}else c.strokeStyle='#172037';c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}const d=this.dur();for(let t=0;t<d;t+=.5){const x=t/d*w;c.strokeStyle=t%1===0?'#27334f':'#172037';c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}if(this.pitchCurve.length){c.strokeStyle='#20d6b5';c.lineWidth=2*devicePixelRatio;c.beginPath();this.pitchCurve.forEach((p,i)=>{const x=p.time/d*w,y=(96-p.midi)/48*h;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}for(const n of this.notes){const r=this.rect(n);c.fillStyle=n.sel?'#20d6b5':'#7c5cff';c.globalAlpha=.88;c.beginPath();roundRect(c,r.x,r.y,r.w,r.h,8*devicePixelRatio);c.fill();c.globalAlpha=1;c.fillStyle='#fff';c.fillText(midiToNote(n.midi),r.x+8,r.y+14*devicePixelRatio)}}
}
function roundRect(c,x,y,w,h,r){c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r)}
