export const FX_DEFS=[['Noise gate',['Threshold','Release']],['EQ',['Low','Mid','High']],['Compressor',['Threshold','Ratio','Attack','Release']],['De-esser',['Frequency','Amount']],['Saturation',['Drive','Tone']],['Doubler',['Width','Delay']],['Chorus',['Rate','Depth','Mix']],['Delay',['Time','Feedback','Mix']],['Reverb',['Size','Damping','Mix']],['Limiter',['Ceiling','Release']]];
export class FxRack{
  constructor(ctx){this.ctx=ctx;this.input=ctx.createGain();this.output=ctx.createGain();this.modules={};this.buildNodes();this.input.connect(this.gate).connect(this.eqLow).connect(this.eqMid).connect(this.eqHigh).connect(this.comp).connect(this.saturator).connect(this.chorusDelay).connect(this.delay).connect(this.reverb).connect(this.limiter).connect(this.output)}
  buildNodes(){const c=this.ctx;this.gate=c.createDynamicsCompressor();this.eqLow=c.createBiquadFilter();this.eqMid=c.createBiquadFilter();this.eqHigh=c.createBiquadFilter();this.comp=c.createDynamicsCompressor();this.saturator=c.createWaveShaper();this.chorusDelay=c.createDelay(.05);this.delay=c.createDelay(1);this.reverb=c.createConvolver();this.limiter=c.createDynamicsCompressor();this.eqLow.type='lowshelf';this.eqLow.frequency.value=160;this.eqMid.type='peaking';this.eqMid.frequency.value=1800;this.eqMid.Q.value=1;this.eqHigh.type='highshelf';this.eqHigh.frequency.value=7200;this.chorusDelay.delayTime.value=.012;this.delay.delayTime.value=.22;this.limiter.threshold.value=-2;this.limiter.knee.value=0;this.limiter.ratio.value=20;this.limiter.attack.value=.002;this.limiter.release.value=.08;this.reverb.buffer=this.impulse(.9,.35);this.setDrive(10)}
  impulse(seconds,decay){const len=Math.max(1,this.ctx.sampleRate*seconds),buf=this.ctx.createBuffer(2,len,this.ctx.sampleRate);for(let ch=0;ch<2;ch++){const d=buf.getChannelData(ch);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay*5)}return buf}
  setDrive(v){const n=2048,curve=new Float32Array(n),k=Number(v)*4;for(let i=0;i<n;i++){const x=i*2/n-1;curve[i]=(1+k)*x/(1+k*Math.abs(x))}this.saturator.curve=curve;this.saturator.oversample='2x'}
  update(settings){const fx=settings.fx||{};this.eqLow.gain.value=(fx.EQ?.Low??50-50)/3;this.eqMid.gain.value=(fx.EQ?.Mid??50-50)/3;this.eqHigh.gain.value=(fx.EQ?.High??50-50)/3;this.comp.threshold.value=-10-(fx.Compressor?.Threshold??35);this.comp.ratio.value=1+(fx.Compressor?.Ratio??35)/12;this.setDrive(fx.Saturation?.Drive??15);this.chorusDelay.delayTime.value=.004+(fx.Chorus?.Depth??25)/1800;this.delay.delayTime.value=(fx.Delay?.Time??30)/100*0.9;this.limiter.threshold.value=-.5-(fx.Limiter?.Ceiling??10)/10}
}
export function renderFxRack(container,state,onChange){container.innerHTML='';for(const [name,controls] of FX_DEFS){state.fx[name] ||= {enabled:name==='Limiter'};const mod=document.createElement('article');mod.className='fx-module';mod.innerHTML=`<div class="fx-head"><h3>${name}</h3><label class="switch"><input type="checkbox" ${state.fx[name].enabled?'checked':''}><span>On</span></label></div>`;const enable=mod.querySelector('input');enable.addEventListener('change',()=>{state.fx[name].enabled=enable.checked;onChange()});for(const ctl of controls){state.fx[name][ctl] ??= 50;const lab=document.createElement('label');lab.textContent=ctl;const range=document.createElement('input');range.type='range';range.min=0;range.max=100;range.value=state.fx[name][ctl];const span=document.createElement('span');span.textContent=' '+range.value;range.addEventListener('input',()=>{state.fx[name][ctl]=Number(range.value);span.textContent=' '+range.value;onChange()});lab.append(range,span);mod.append(lab)}container.append(mod)}}
