// Advanced playable layer: turns the laboratory, matrix, routing, sequencer and FX library into audio controls.
const advanced={dragSource:null,fxModules:[],sequenceTimer:null,sequenceNote:null,source:{mode:'wavetable',name:'Factory table'}};
const routeObject=route=>Array.isArray(route)?{source:route[0],destination:route[1],amount:+route[2]}:{...route,amount:+route.amount};
state.routes=state.routes.map(routeObject);
const destinationFor=control=>{const name=$('span',control)?.textContent||control.dataset.target,osc=control.closest('.osc-card'),filter=control.closest('.filter-card'),fxCard=control.closest('.fx-card');if(osc)return `OSC ${'ABC'[$$('.osc-card').indexOf(osc)]} · ${name==='POSITION'?'WT POS':name}`;if(filter)return `FILTER ${'AB'[$$('.filter-card').indexOf(filter)]} · ${name}`;if(fxCard)return `FX A · ${name}`;return name};
function publishAdvanced(){synthSettings.routes=state.routes.map(routeObject);synthSettings.fxModules=[...advanced.fxModules];synthSettings.source={...(synthSettings.source||{}),...advanced.source};sendSynthSettings()}
function addRoute(source,destination,amount=45){state.routes.push({source,destination,amount});matrix();publishAdvanced();toast(`${source} → ${destination}`)}
function matrix(){const rows=state.routes.map(routeObject);state.routes=rows;$('#matrixTable').innerHTML=`<div class="matrix-row"><b>SOURCE</b><b>DESTINATION</b><b>AMOUNT</b><b></b></div>`+rows.map((r,i)=>`<div class="matrix-row"><b>${r.source}</b><span>${r.destination}</span><input type="range" min="-100" max="100" value="${r.amount}" data-route="${i}"><button data-remove="${i}">×</button></div>`).join('');$$('[data-remove]').forEach(b=>b.onclick=()=>{state.routes.splice(+b.dataset.remove,1);matrix();publishAdvanced()});$$('[data-route]').forEach(input=>input.oninput=()=>{state.routes[+input.dataset.route].amount=+input.value;publishAdvanced()})}
matrix();
$('#addRoute').onclick=()=>addRoute('MACRO 2','FILTER B · CUTOFF',32);
$$('.source-chip').forEach(chip=>{chip.ondragstart=e=>{advanced.dragSource=chip.textContent.split(' ·')[0];e.dataTransfer?.setData('text/plain',advanced.dragSource)}});
$$('.assignable').forEach(target=>{target.ondragover=e=>{e.preventDefault();target.classList.add('drop-ready')};target.ondragleave=()=>target.classList.remove('drop-ready');target.ondrop=e=>{e.preventDefault();target.classList.remove('drop-ready');addRoute(e.dataTransfer?.getData('text/plain')||advanced.dragSource,destinationFor(target))}});
const granular=$$('.advanced-grid .lab-module')[0],spectral=$$('.advanced-grid .lab-module')[1];
function syncLabs(){const g=$$('input[type=range]',granular).map(x=>+x.value/100),s=$$('input[type=range]',spectral).map(x=>+x.value/100);synthSettings.granular={size:g[0],density:g[1],spray:g[2],texture:g[3]};synthSettings.spectral={blur:s[0],shift:s[1],formant:s[2],stretch:s[3]};publishAdvanced()}
$$('input[type=range]',granular).concat($$('input[type=range]',spectral)).forEach(input=>input.oninput=syncLabs);syncLabs();
const baseApplyKnob=applyKnob;
applyKnob=function(control,value){baseApplyKnob(control,value);const filter=control?.closest('.filter-card'),name=$('span',control)?.textContent;if(filter){const id=$$('.filter-card').indexOf(filter),key=id?'filterB':'filterA',f=synthSettings[key]||{};if(name==='CUTOFF')f.cutoff=.01+value/180;if(name==='RESONANCE')f.resonance=value/120;if(name==='MIX')f.mix=value/100;if(name==='DRIVE')f.drive=value/100;synthSettings[key]=f;drawFilter($('.filter-canvas',filter),id);publishAdvanced()}};
synthSettings.filterA={cutoff:synthSettings.cutoff,resonance:synthSettings.resonance,mix:synthSettings.filterMix};synthSettings.filterB={cutoff:.26,resonance:.46,mix:.42};synthSettings.filterRouting='PARALLEL';
$$('#filterRouting button').forEach(button=>button.onclick=()=>{$$('#filterRouting button').forEach(b=>b.classList.toggle('active',b===button));synthSettings.filterRouting=button.textContent;publishAdvanced();toast(`FILTERS · ${button.textContent}`)});
async function importAudio(selection,mode){const files=[...(selection?.length===undefined?[selection]:selection)].filter(Boolean);if(!files.length)return;try{await audioReady();const sources=[];for(const file of files){const decoded=await audio.decodeAudioData(await file.arrayBuffer()),channel=decoded.getChannelData(0),stride=Math.max(1,Math.ceil(channel.length/32768)),buffer=Array.from({length:Math.ceil(channel.length/stride)},(_,i)=>channel[Math.min(channel.length-1,i*stride)]),table=Array.from({length:256},(_,i)=>channel[Math.min(channel.length-1,Math.floor(i*channel.length/256))]);sources.push({name:file.name,buffer,table})}advanced.source={mode,name:sources.map(x=>x.name).join(', '),buffer:sources[0].buffer,table:sources[0].table,multisamples:mode==='multisample'?sources.map((x,i)=>({...x,root:36+Math.round(i*48/Math.max(1,sources.length-1))})):[]};worklet?.port.postMessage({type:'source',source:advanced.source});publishAdvanced();toast(`${mode.toUpperCase()} LOADED · ${files.length} SOURCE${files.length>1?'S':''}`)}catch(error){console.error(error);toast(`SOURCE ERROR · ${error.message}`)}}
const sourceInputs=$$('.source-actions input');sourceInputs[0].onchange=e=>importAudio(e.target.files,'wavetable');sourceInputs[1].onchange=e=>importAudio(e.target.files,'sample');sourceInputs[2].onchange=e=>importAudio(e.target.files,'multisample');
synthSettings.oscModes=['wavetable','wavetable','wavetable'];
$$('.engine-modes button').forEach(button=>button.onclick=()=>{const group=button.parentElement,card=button.closest('.osc-card'),index=$$('.osc-card').indexOf(card),mode=button.textContent.toLowerCase();$$('button',group).forEach(b=>b.classList.toggle('active',b===button));synthSettings.oscModes[index]=mode;advanced.source.mode=mode==='multi'?'multisample':mode;publishAdvanced();toast(`OSC ${'ABC'[index]} · ${button.textContent} ENGINE ACTIVE`)});
function insertFx(name){if(advanced.fxModules.includes(name))return toast(`${name} ALREADY INSERTED`);advanced.fxModules.push(name);const card=document.createElement('article');card.className='module fx-card inserted-fx';card.innerHTML=`<div class="module-title"><div><span class="power on"></span><small>LIVE INSERT</small><h3>${name}</h3></div><button aria-label="Remove ${name}">×</button></div><p>ACTIVE DSP INSERT · CLICK × TO REMOVE</p>`;card.querySelector('button').onclick=()=>{advanced.fxModules=advanced.fxModules.filter(x=>x!==name);card.remove();publishAdvanced();toast(`${name} REMOVED`)};$('#fxRack').append(card);publishAdvanced();if(master)master.gain.value=Math.min(.9,+$('#masterVolume').value*(1+advanced.fxModules.length*.025));updateDistortionCurve(2.2+advanced.fxModules.length*.24);toast(`${name} INSERTED`)}
$$('#fxLibrary span').forEach(chip=>{chip.draggable=true;chip.onclick=()=>insertFx(chip.textContent);chip.ondragstart=e=>e.dataTransfer?.setData('text/fx',chip.textContent)});$('#fxRack').ondragover=e=>e.preventDefault();$('#fxRack').ondrop=e=>{e.preventDefault();insertFx(e.dataTransfer?.getData('text/fx'))};
const baseCompatibilitySynth=createCompatibilitySynth;
createCompatibilitySynth=function(context){const node=baseCompatibilitySynth(context),post=node.port.postMessage;node.port.postMessage=data=>{if(data.type!=='settings')return post(data);const rich=data.settings,g=(rich.granular?.texture||0)*.18,sp=rich.spectral||{},routeCut=(rich.routes||[]).filter(r=>(r.destination||'').includes('FILTER')).reduce((sum,r)=>sum+(r.amount||0)/1200,0),a=rich.filterA||{},b=rich.filterB||{};post({...data,settings:{...rich,cutoff:Math.max(.01,Math.min(.48,rich.filterRouting==='PARALLEL'?((a.cutoff||.18)+(b.cutoff||.24))/2:Math.min(a.cutoff||.18,b.cutoff||.24)+routeCut)),resonance:((a.resonance||.2)+(b.resonance||.3))/2,filterMix:(a.mix||.5),noiseLevel:(rich.noiseLevel||0)+(rich.granular?.spray||0)*.035,osc:rich.osc.map((o,i)=>({...o,position:Math.max(0,Math.min(1,o.position+(sp.shift-.5)*.3)),level:o.level*(1+g+(sp.stretch||0)*.12)}))}})};return node};
const pattern=[50,null,53,null,57,null,60,null,62,null,57,null,53,null,48,null],velocity=[72,32,55,90,20,45,62,34,84,41,77,26,59,44,88,65];
function sequencerTick(){const step=state.step++%16;$$('.step').forEach((el,i)=>el.classList.toggle('playing',i===step));if(advanced.sequenceNote!==null)noteOff(advanced.sequenceNote);advanced.sequenceNote=pattern[step];if(advanced.sequenceNote!==null)noteOn(advanced.sequenceNote,null,velocity[step]/100)}
function stopSequencer(){clearInterval(advanced.sequenceTimer);advanced.sequenceTimer=null;if(advanced.sequenceNote!==null)noteOff(advanced.sequenceNote);advanced.sequenceNote=null;state.seq=false;$('#seqPlay').textContent='▶';$$('.step').forEach(el=>el.classList.remove('playing'))}
$('#seqPlay').onclick=()=>{if(advanced.sequenceTimer)return stopSequencer();state.seq=false;state.step=0;sequencerTick();const bpm=Math.max(40,Math.min(240,+$('#tempo').value||124));advanced.sequenceTimer=setInterval(sequencerTick,60000/bpm/4);$('#seqPlay').textContent='■';toast('SEQUENCER PLAYING NOTES')};
const oldNoteOn=noteOn;noteOn=async function(note,el,velocity=.78){heldNotes.add(note);try{const node=await audioReady();if(!heldNotes.has(note))return;node.port.postMessage({type:'noteOn',note,velocity});state.activeNotes.add(note);el?.classList.add('pressed');$('#voiceCount').textContent=String(state.activeNotes.size).padStart(2,'0')}catch(error){heldNotes.delete(note);console.error(error);toast(`AUDIO ERROR · ${error.message}`)}};
setInterval(()=>{const activity=state.activeNotes.size*4+advanced.fxModules.length*3+(advanced.sequenceTimer?3:0)+(audio?.state==='running'?2:0),value=Math.max(1,Math.min(96,Math.round(activity+Math.random()*3)));$('#cpuMeter').textContent=String(value).padStart(2,'0')+'%';$('.footer-right i').style.height=`${Math.max(5,value*.6)}px`},650);
publishAdvanced();

// Oscillator voice controls and the routing map now drive DSP instead of serving as static decoration.
synthSettings.oscRoutes=['A','B','MASTER'];
const routedApplyKnob=applyKnob;
applyKnob=function(control,value){routedApplyKnob(control,value);const card=control?.closest('.osc-card'),name=$('span',control)?.textContent;if(!card)return;const osc=synthSettings.osc[$$('.osc-card').indexOf(card)];if(name==='UNISON')osc.unison=1+Math.round(value/17);if(name==='DETUNE')osc.detune=value/40;if(name==='WIDTH')osc.width=value/100;if(name==='PAN')osc.pan=value/100;if(name==='PHASE')osc.phase=value/100;if(name==='RAND')osc.random=value/100;publishAdvanced()};
function renderOscRouting(){const map=$('.routing-map');map.innerHTML=synthSettings.oscRoutes.map((route,index)=>`<label><span>OSC ${'ABC'[index]}</span><select data-osc-route="${index}"><option ${route==='A'?'selected':''}>A</option><option ${route==='B'?'selected':''}>B</option><option ${route==='MASTER'?'selected':''}>MASTER</option></select></label>`).join('')+'<strong>FILTER A + FILTER B + DIRECT MASTER</strong>';$$('[data-osc-route]').forEach(select=>select.onchange=()=>{synthSettings.oscRoutes[+select.dataset.oscRoute]=select.value;publishAdvanced();toast(`OSC ${'ABC'[+select.dataset.oscRoute]} → ${select.value}`)})}
renderOscRouting();
$$('.osc-card').forEach(card=>$$('.knob-control',card).forEach(control=>applyKnob(control,knobValue(control))));
