const VERSION = 1;
const MAX_FILE_BYTES = 80 * 1024 * 1024;
const WORKLET_URL = 'reverb-worklet.js';
const PARAMS = {
  mix:{label:'Mix',min:0,max:1,step:.01,unit:'%',scale:v=>Math.round(v*100)}, decay:{label:'Decay',min:.2,max:20,step:.1,unit:' s',scale:v=>v.toFixed(1)}, size:{label:'Size',min:.1,max:1,step:.01,unit:'%',scale:v=>Math.round(v*100)}, predelay:{label:'Predelay',min:0,max:250,step:1,unit:' ms',scale:v=>Math.round(v)}, lowCut:{label:'Low Cut',min:20,max:1000,step:1,unit:' Hz',scale:v=>Math.round(v)}, highCut:{label:'High Cut',min:1500,max:20000,step:10,unit:' Hz',scale:v=>Math.round(v)}, damping:{label:'Damping',min:0,max:1,step:.01,unit:'%',scale:v=>Math.round(v*100)}, modRate:{label:'Mod Rate',min:0,max:8,step:.01,unit:' Hz',scale:v=>v.toFixed(2)}, modDepth:{label:'Mod Depth',min:0,max:1,step:.01,unit:'%',scale:v=>Math.round(v*100)}, stereoWidth:{label:'Stereo Width',min:0,max:2,step:.01,unit:'%',scale:v=>Math.round(v*100)}, inputGain:{label:'Input Gain',min:-24,max:24,step:.1,unit:' dB',scale:v=>v.toFixed(1)}, outputGain:{label:'Output Gain',min:-24,max:24,step:.1,unit:' dB',scale:v=>v.toFixed(1)}
};
const DEFAULT = {name:'Default Plate',category:'Essentials',mode:'Plate',color:'Dark Vintage',mix:.35,decay:3.2,size:.58,predelay:24,lowCut:120,highCut:9500,damping:.48,modRate:.38,modDepth:.22,stereoWidth:1.15,inputGain:0,outputGain:0,wetSolo:false,bypass:false,version:VERSION,createdDate:new Date().toISOString()};
const FACTORY = [
 p('Essentials','Default Plate','Plate','Dark Vintage',[.35,3.2,.58,24,120,9500,.48,.38,.22,1.15,0,0]), p('Essentials','Small Tracking Room','Room','Clean Modern',[.22,1.1,.32,8,150,12000,.28,.12,.08,.92,0,-.5]), p('Essentials','Wide Vocal Hall','Hall','Bright 80s',[.31,4.8,.72,38,95,14000,.34,.55,.26,1.42,1,-1]),
 p('Plates','Bronze Vocal Plate','Plate','Dark Vintage',[.42,3.8,.64,32,140,8200,.58,.44,.25,1.22,0,-1]), p('Plates','Gloss Plate 86','Plate','Bright 80s',[.36,2.6,.54,18,100,16000,.22,.72,.18,1.3,.5,-.5]), p('Plates','Short Drum Plate','Plate','Clean Modern',[.28,1.5,.4,6,180,11000,.3,.2,.1,1.05,0,0]),
 p('Rooms','Wood Studio A','Room','Dark Vintage',[.26,1.8,.44,12,170,7600,.55,.18,.12,1.05,0,-.3]), p('Rooms','Bright Live Room','Room','Bright 80s',[.24,1.35,.38,5,120,15500,.2,.32,.09,1.18,0,0]), p('Rooms','Tight Ambience Room','Ambience','Clean Modern',[.18,.65,.26,2,210,13500,.16,.05,.04,.82,0,.5]),
 p('Halls','Concert Bloom','Hall','Clean Modern',[.38,6.4,.82,46,80,12500,.42,.41,.2,1.35,0,-1.5]), p('Halls','Tape Dark Hall','Hall','Dark Vintage',[.45,7.8,.88,58,160,6800,.76,.28,.32,1.24,1,-2]), p('Halls','Digital Grand Hall','Hall','Bright 80s',[.34,5.6,.78,34,90,17000,.24,.64,.22,1.5,0,-1]),
 p('Chambers','Stone Chamber','Chamber','Dark Vintage',[.4,4.2,.62,28,130,7800,.62,.31,.18,1.12,0,-1]), p('Chambers','Pop Chamber','Chamber','Bright 80s',[.32,2.9,.52,22,100,14500,.25,.52,.14,1.28,.5,-.5]), p('Chambers','Clean Chamber','Chamber','Clean Modern',[.3,3.4,.56,18,90,13500,.31,.2,.1,1.1,0,0]),
 p('Huge Spaces','Cathedral Nave','Cathedral','Dark Vintage',[.48,12.5,.96,82,110,7200,.82,.2,.38,1.38,0,-3]), p('Huge Spaces','Celestial Dome','Cathedral','Clean Modern',[.43,14.8,1,110,70,15000,.46,.33,.28,1.62,-1,-3.5]), p('Huge Spaces','Endless 80s Cloud','Cathedral','Bright 80s',[.5,10.5,.92,96,100,18000,.28,.78,.35,1.7,0,-4])
];
function p(category,name,mode,color,v){const keys=['mix','decay','size','predelay','lowCut','highCut','damping','modRate','modDepth','stereoWidth','inputGain','outputGain']; return Object.assign({name,category,mode,color,wetSolo:false,bypass:false,version:VERSION,createdDate:'factory',locked:true},Object.fromEntries(keys.map((k,i)=>[k,v[i]])));}
const $ = id => document.getElementById(id);
let ctx, source, worklet, dryGain, buffer, startAt=0, started=0, playing=false, userPresets=loadUserPresets(), current={...DEFAULT};
const els = ['supportStatus','audioFile','fileMeta','playBtn','stopBtn','exportWavBtn','wetSoloBtn','bypassBtn','waveform','presetCategory','presetSelect','presetName','savePresetBtn','duplicatePresetBtn','exportPresetBtn','importPresetInput','resetDefaultBtn','presetMessage','mode','color','controls','readout','errorBox','currentModePill','presetLock'].reduce((a,id)=>(a[id]=$(id),a),{});
init();
function init(){
  if(!window.AudioContext || !window.AudioWorkletNode || !window.OfflineAudioContext) return unsupported('This browser does not support the Web Audio API features required by this app. Try current Chrome, Edge, Firefox, or Safari.');
  els.supportStatus.textContent='Ready: Web Audio API and AudioWorklet supported.'; buildControls(); bind(); refreshPresets(); applyPreset(DEFAULT); drawEmpty();
}
function unsupported(msg){els.supportStatus.textContent=msg; els.supportStatus.style.color='var(--danger)'; showError(msg)}
function buildControls(){els.controls.innerHTML=Object.entries(PARAMS).map(([key,c])=>`<div class="control"><div class="control-top"><strong>${c.label}</strong><span class="value" id="${key}Value"></span></div><input id="${key}" type="range" min="${c.min}" max="${c.max}" step="${c.step}"></div>`).join('')}
function bind(){
  els.audioFile.addEventListener('change', loadFile); els.playBtn.onclick=play; els.stopBtn.onclick=stop; els.exportWavBtn.onclick=exportWav; els.wetSoloBtn.onclick=()=>setBool('wetSolo',!current.wetSolo); els.bypassBtn.onclick=()=>setBool('bypass',!current.bypass);
  els.mode.onchange=()=>setState({mode:els.mode.value}); els.color.onchange=()=>setState({color:els.color.value});
  Object.keys(PARAMS).forEach(k=>$(k).addEventListener('input',e=>setState({[k]:Number(e.target.value)})));
  els.presetCategory.onchange=refreshPresetSelect; els.presetSelect.onchange=()=>applyPreset(allPresets().find(x=>x.id===els.presetSelect.value)||DEFAULT); els.savePresetBtn.onclick=saveCurrentPreset; els.duplicatePresetBtn.onclick=duplicatePreset; els.exportPresetBtn.onclick=exportPreset; els.importPresetInput.onchange=importPreset; els.resetDefaultBtn.onclick=()=>applyPreset(DEFAULT);
}
async function ensureAudio(){if(ctx) return; ctx=new AudioContext(); await ctx.audioWorklet.addModule(WORKLET_URL); worklet=new AudioWorkletNode(ctx,'vintage-reverb-processor',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[2]}); dryGain=ctx.createGain(); worklet.connect(ctx.destination); sendWorkletState(); applyAudioParams();}
async function loadFile(e){clearError(); const file=e.target.files[0]; if(!file) return; if(file.size>MAX_FILE_BYTES){showError('File is larger than 80 MB. Please choose a smaller file for reliable in-browser decoding.'); e.target.value=''; return} try{await ensureAudio(); const ab=await file.arrayBuffer(); buffer=await ctx.decodeAudioData(ab); els.fileMeta.textContent=`${file.name} • ${buffer.duration.toFixed(2)} s • ${buffer.numberOfChannels} channel(s)`; els.playBtn.disabled=els.stopBtn.disabled=els.exportWavBtn.disabled=false; drawWaveform(buffer)}catch(err){showError(`Could not decode this audio file: ${err.message}`)}}
function makeSource(){if(source) source.disconnect(); source=ctx.createBufferSource(); source.buffer=buffer; source.connect(worklet); source.onended=()=>{if(playing) stop(false)}}
async function play(){if(!buffer) return; await ensureAudio(); await ctx.resume(); makeSource(); started=ctx.currentTime; source.start(0,startAt); playing=true; els.playBtn.textContent='Pause'; els.playBtn.onclick=pause; tick()}
function pause(){if(!playing) return; startAt=(ctx.currentTime-started+startAt)%buffer.duration; stop(false)}
function stop(reset=true){try{source?.stop()}catch{} playing=false; if(reset) startAt=0; els.playBtn.textContent='Play'; els.playBtn.onclick=play; drawWaveform(buffer)}
function tick(){if(!playing) return; const pos=(ctx.currentTime-started+startAt)/buffer.duration; drawWaveform(buffer,pos); requestAnimationFrame(tick)}
function setBool(k,v){setState({[k]:v}); els[k+'Btn']?.classList.toggle('active',v)}
function setState(partial){current={...current,...partial}; syncUI(); applyAudioParams(); sendWorkletState();}
function applyPreset(pr){current={...DEFAULT,...pr,version:pr.version||VERSION}; syncUI(); applyAudioParams(); sendWorkletState(); message(`Loaded “${current.name}”.`)}
function syncUI(){els.mode.value=current.mode; els.color.value=current.color; els.currentModePill.textContent=current.mode; Object.entries(PARAMS).forEach(([k,c])=>{const el=$(k); el.value=current[k]; $(k+'Value').textContent=`${c.scale(current[k])}${c.unit}`}); els.wetSoloBtn.classList.toggle('active',current.wetSolo); els.bypassBtn.classList.toggle('active',current.bypass); els.presetName.value=current.name; const locked=!!current.locked; els.presetLock.textContent=locked?'Factory locked':'User editable'; els.presetName.disabled=locked; els.savePresetBtn.disabled=locked; els.readout.innerHTML=`Mode: <b>${current.mode}</b><br>Color: <b>${current.color}</b><br>Mix: <b>${Math.round(current.mix*100)}%</b><br>Decay: <b>${current.decay.toFixed(1)} s</b>`}
function applyAudioParams(node=worklet, ac=ctx){if(!node||!ac) return; Object.keys(PARAMS).forEach(k=>node.parameters.get(k)?.setTargetAtTime(current[k],ac.currentTime,.015))}
function sendWorkletState(node=worklet){node?.port.postMessage({type:'state',state:{mode:current.mode,color:current.color,wetSolo:current.wetSolo,bypass:current.bypass}})}
function allPresets(){return [...FACTORY.map(x=>({...x,id:'factory:'+x.category+':'+x.name})),...userPresets.map(x=>({...x,locked:false,id:'user:'+x.category+':'+x.name}))]}
function refreshPresets(){const cats=[...new Set(allPresets().map(p=>p.category))]; els.presetCategory.innerHTML=cats.map(c=>`<option>${c}</option>`).join(''); refreshPresetSelect()}
function refreshPresetSelect(){const cat=els.presetCategory.value; const ps=allPresets().filter(p=>p.category===cat); els.presetSelect.innerHTML=ps.map(p=>`<option value="${p.id}">${p.locked?'🔒':'✎'} ${p.name}</option>`).join('')}
function saveCurrentPreset(){const name=els.presetName.value.trim()||current.name; const preset={...current,name,locked:false,version:VERSION,createdDate:current.createdDate==='factory'?new Date().toISOString():current.createdDate}; const i=userPresets.findIndex(p=>p.name===preset.name&&p.category===preset.category); if(i>=0) userPresets[i]=preset; else userPresets.push(preset); persist(); current=preset; refreshPresets(); message(`Saved user preset “${name}”.`)}
function duplicatePreset(){const copy={...current,name:`${current.name} Copy`,category:current.category||'User',locked:false,createdDate:new Date().toISOString(),version:VERSION}; userPresets.push(copy); persist(); refreshPresets(); applyPreset(copy)}
function exportPreset(){const preset={...current,name:els.presetName.value.trim()||current.name,locked:undefined,version:VERSION,createdDate:current.createdDate==='factory'?new Date().toISOString():current.createdDate}; download(`${safe(preset.name)}.json`, JSON.stringify(preset,null,2), 'application/json')}
async function importPreset(e){const file=e.target.files[0]; if(!file) return; try{const parsed=JSON.parse(await file.text()); const valid=validatePreset(parsed); userPresets.push(valid); persist(); refreshPresets(); applyPreset(valid); message(`Imported “${valid.name}”.`)}catch(err){showError(`Preset import failed: ${err.message}`)} finally{e.target.value=''}}
function validatePreset(x){if(!x||typeof x!=='object') throw Error('Preset file is not an object.'); for(const k of ['name','category','mode','color','version','createdDate']) if(typeof x[k]!=='string'&&k!=='version') throw Error(`Missing or invalid ${k}.`); if(!['Plate','Room','Hall','Chamber','Cathedral','Ambience'].includes(x.mode)) throw Error('Invalid reverb mode.'); if(!['Dark Vintage','Bright 80s','Clean Modern'].includes(x.color)) throw Error('Invalid color mode.'); const out={...DEFAULT,...x,locked:false}; for(const [k,c] of Object.entries(PARAMS)){const n=Number(x[k]); if(!Number.isFinite(n)||n<c.min||n>c.max) throw Error(`Invalid ${c.label}.`); out[k]=n} if(!Number.isFinite(Number(x.version))) throw Error('Invalid version number.'); out.wetSolo=!!x.wetSolo; out.bypass=!!x.bypass; out.version=Number(x.version); return out}
function loadUserPresets(){try{return JSON.parse(localStorage.getItem('echoAtelierPresets')||'[]').filter(Boolean)}catch{return[]}}
function persist(){localStorage.setItem('echoAtelierPresets',JSON.stringify(userPresets))}
async function exportWav(){if(!buffer) return; clearError(); els.exportWavBtn.disabled=true; els.exportWavBtn.textContent='Rendering…'; try{const off=new OfflineAudioContext(2, Math.ceil(buffer.duration*buffer.sampleRate), buffer.sampleRate); await off.audioWorklet.addModule(WORKLET_URL); const node=new AudioWorkletNode(off,'vintage-reverb-processor',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[2]}); const src=off.createBufferSource(); src.buffer=buffer; src.connect(node).connect(off.destination); sendWorkletState(node); applyAudioParams(node,off); src.start(); const rendered=await off.startRendering(); download('echo-atelier-render.wav', encodeWav(rendered), 'audio/wav'); message('WAV export complete.')}catch(err){showError(`Export failed: ${err.message}`)}finally{els.exportWavBtn.disabled=false; els.exportWavBtn.textContent='Export WAV'}}
function encodeWav(b){const ch=b.numberOfChannels, len=b.length*ch*2+44, view=new DataView(new ArrayBuffer(len)); let o=0; const s=x=>{for(let i=0;i<x.length;i++)view.setUint8(o++,x.charCodeAt(i))}; s('RIFF'); view.setUint32(o,len-8,true); o+=4; s('WAVEfmt '); view.setUint32(o,16,true); o+=4; view.setUint16(o,1,true); o+=2; view.setUint16(o,ch,true); o+=2; view.setUint32(o,b.sampleRate,true); o+=4; view.setUint32(o,b.sampleRate*ch*2,true); o+=4; view.setUint16(o,ch*2,true); o+=2; view.setUint16(o,16,true); o+=2; s('data'); view.setUint32(o,len-44,true); o+=4; const data=[...Array(ch)].map((_,i)=>b.getChannelData(i)); for(let i=0;i<b.length;i++)for(let c=0;c<ch;c++){const v=Math.max(-1,Math.min(1,data[c][i])); view.setInt16(o,v<0?v*0x8000:v*0x7fff,true); o+=2} return view.buffer}
function drawEmpty(){const c=els.waveform, g=c.getContext('2d'); g.clearRect(0,0,c.width,c.height); g.fillStyle='#111722'; g.fillRect(0,0,c.width,c.height); g.fillStyle='#59657d'; g.textAlign='center'; g.fillText('Load an audio file to display the waveform',c.width/2,c.height/2)}
function drawWaveform(b,playhead=0){if(!b) return drawEmpty(); const c=els.waveform,g=c.getContext('2d'),w=c.width,h=c.height,data=b.getChannelData(0),step=Math.ceil(data.length/w); g.clearRect(0,0,w,h); g.fillStyle='#091019'; g.fillRect(0,0,w,h); g.strokeStyle='#d7a64a'; g.beginPath(); for(let x=0;x<w;x++){let min=1,max=-1; for(let j=0;j<step;j++){const v=data[x*step+j]||0; if(v<min)min=v; if(v>max)max=v} g.moveTo(x,(1+min)*h/2); g.lineTo(x,(1+max)*h/2)} g.stroke(); if(playhead){g.strokeStyle='#73d7ff'; g.beginPath(); g.moveTo(playhead*w,0); g.lineTo(playhead*w,h); g.stroke()}}
function download(name,content,type){const blob=content instanceof Blob?content:new Blob([content],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function safe(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'preset'}
function message(msg){els.presetMessage.textContent=msg; clearError()} function showError(msg){els.errorBox.hidden=false; els.errorBox.textContent=msg} function clearError(){els.errorBox.hidden=true; els.errorBox.textContent=''}
