const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const state={octave:4,activeNotes:new Set(),routes:[['LFO 1','OSC A · WT POS',38],['ENV 2','FILTER A · CUTOFF',72],['MACRO 1','FX A · DRIVE',45],['LFO 2','OSC B · WARP 1',26]],preset:'SILVER HORIZON',presetIndex:0,presetCategory:'ALL',seq:false,step:0};
const knobs=(items,accent='var(--orange)')=>items.map(([name,val])=>`<div class="knob-control assignable" data-target="${name}"><i class="knob" style="--v:${val};--accent:${accent}"></i><span>${name}</span><b>${val}</b></div>`).join('');
const oscData=[['A','PRISMATIC TIDE',[["POSITION",32],["UNISON",7],["DETUNE",18],["WIDTH",84],["LEVEL",78],["PAN",50],["PHASE",23],["RAND",16]]],['B','MIDNIGHT GLASS',[["POSITION",64],["UNISON",4],["DETUNE",10],["WIDTH",62],["LEVEL",56],["PAN",50],["PHASE",52],["RAND",34]]],['C','EMBER VOX',[["POSITION",47],["UNISON",2],["DETUNE",6],["WIDTH",48],["LEVEL",42],["PAN",50],["PHASE",11],["RAND",8]]]];
$('#oscGrid').innerHTML=oscData.map(([id,name,ks],idx)=>`<article class="module osc-card"><div class="module-title"><div><span class="power on"></span><small>OSCILLATOR ${id}</small><h3>${name}</h3></div><b>${idx===2?'−12':'± 00'} SEMI</b></div><div class="engine-modes"><button class="active">WAVETABLE</button><button>SAMPLE</button><button>MULTI</button><button>GRAIN</button><button>SPECTRAL</button></div><div class="visual"><canvas class="wave-canvas" data-wave="${idx}" width="520" height="170"></canvas><span class="visual-label">FRAME ${24+idx*19} / 128</span><span class="visual-tag">3D TABLE</span></div><div class="osc-controls">${knobs(ks)}</div><div class="warp-row"><div class="warp"><div class="warp-head"><span>WARP 1</span><b>${['BEND +','FM FROM B','FORMANT'][idx]}</b></div><input type="range" value="${38+idx*13}"></div><div class="warp"><div class="warp-head"><span>WARP 2</span><b>${['FOLD','MIRROR','QUANTIZE'][idx]}</b></div><input type="range" value="${21+idx*9}"></div></div></article>`).join('');
$('#filterGrid').innerHTML=['A','B'].map((id,i)=>`<article class="module filter-card"><div class="module-title"><div><span class="power on"></span><small>FILTER ${id}</small><h3>${i?'FORMANT / VOWEL':'LOW PASS · 24 DB'}</h3></div><b>${i?'PARALLEL':'ROUTE A + C'}</b></div><canvas class="filter-canvas" data-filter="${i}" width="800" height="220"></canvas><div class="filter-controls">${knobs([["CUTOFF",i?45:62],["RESONANCE",i?56:31],["DRIVE",i?24:36],["MIX",i?42:100],["PAN",50]],i?'var(--purple)':'var(--cyan)')}</div></article>`).join('');
$('#envSliders').innerHTML=[['ATTACK',12],['DECAY',42],['SUSTAIN',68],['RELEASE',47]].map(([n,v])=>`<label>${n}<input type="range" value="${v}"></label>`).join('');
$('#lfoGrid').innerHTML=[1,2].map(i=>`<article class="module lfo-card"><div class="module-title"><div><small>LFO ${i}</small><h3>${i===1?'TRIANGLE MORPH':'DRAWN SHAPE'}</h3></div><b>${i===1?'1 / 8':'1 / 2T'}</b></div><canvas class="lfo-canvas" data-lfo="${i}" width="360" height="120"></canvas><span class="source-chip" draggable="true">LFO ${i} · DRAG SOURCE</span></article>`).join('');
function matrix(){ $('#matrixTable').innerHTML=`<div class="matrix-row"><b>SOURCE</b><b>DESTINATION</b><b>AMOUNT</b><b></b></div>`+state.routes.map((r,i)=>`<div class="matrix-row"><b>${r[0]}</b><span>${r[1]}</span><input type="range" value="${r[2]}"><button data-remove="${i}">×</button></div>`).join(''); $$('[data-remove]').forEach(b=>b.onclick=()=>{state.routes.splice(+b.dataset.remove,1);matrix()})} matrix();
$('#macroGrid').innerHTML=Array.from({length:8},(_,i)=>`<div class="macro knob-control"><i class="knob" style="--v:${[38,62,45,28,73,51,19,57][i]};--accent:var(--cyan)"></i><span>MACRO ${i+1}</span><b>${['MOTION','SPACE','GROWL','AIR','PULSE','TONE','DUST','WIDE'][i]}</b></div>`).join('');
const fx=[['DISTORTION','SOFT CLIP',true],['CHORUS','DIMENSION',true],['DELAY','PING PONG',true],['REVERB','ALGORITHM',true],['COMPRESSOR','MULTIBAND',true],['EQ','THREE BAND',true],['FREQ SHIFT','STEREO',false],['UTILITY','MONO BASS',true]];
$('#fxRack').innerHTML=fx.map(([name,type,on],i)=>`<article class="module fx-card ${on?'':'disabled'}"><div class="module-title"><div><span class="power ${on?'on':''}"></span><small>0${i+1} · FX MODULE</small><h3>${name}</h3></div><b>${type}</b></div><div class="fx-visual"></div><div class="fx-controls">${knobs([["MIX",i?42:76],[i===2?'TIME':i===3?'SIZE':'TONE',54],[i===0?'DRIVE':'WIDTH',68]],'var(--purple)')}</div></article>`).join('');
const notes=[['D3',1,16,4],['F3',2,8,4],['A3',3,7,2],['C4',4,4,3],['D4',5,1,2],['F4',6,10,4],['A4',7,13,2],['C5',8,15,2]];
$('#pianoRoll').innerHTML=notes.map(([n,row,col,len])=>`<div class="note-block" style="left:${(col-1)*56+3}px;top:${(8-row)*25+3}px;width:${len*53}px">${n}</div>`).join('');
$('#stepRow').innerHTML=Array.from({length:16},(_,i)=>`<div class="step ${[0,3,6,8,10,14].includes(i)?'active':''}" data-step="${i}">${String(i+1).padStart(2,'0')}<i style="height:${[72,32,55,90,20,45,62,34,84,41,77,26,59,44,88,65][i]/3}px"></i></div>`).join('');
const presets=[['SILVER HORIZON','PAD','WARM / MOTION'],['NEON SUBWAY','BASS','DARK / MONO'],['CERAMIC BLOOM','TEXTURE','GRANULAR'],['FRACTAL PLUCK','LEAD','DIGITAL'],['ORBITAL DUST','TEXTURE','SPECTRAL'],['POLAR CHORD','PAD','WIDE'],['VOLTAGE RUNNER','BASS','SEQUENCED'],['EMBER SIGNAL','LEAD','ANALOG'],['VIOLET MACHINE','TEXTURE','DISTORTED'],['SUBMERGED','BASS','DEEP'],['GLASS AVIARY','LEAD','BRIGHT'],['CIRRUS FIELD','TEXTURE','AIRY']];
function visiblePresets(filter=''){return presets.filter(p=>(state.presetCategory==='ALL'||p[1]===state.presetCategory)&&p.join(' ').toLowerCase().includes(filter.toLowerCase()))}
function listPresets(filter=$('#presetSearch').value){const matches=visiblePresets(filter);$('#presetList').innerHTML=matches.length?matches.map(p=>`<div class="preset-row ${p[0]===state.preset?'selected':''}" data-preset="${p[0]}"><b>${String(presets.indexOf(p)+1).padStart(2,'0')} · ${p[0]}</b><span>${p[1]}</span><span>${p[2]}</span></div>`).join(''):'<p class="empty-presets">NO PATCHES MATCH THIS VIEW</p>';$$('.preset-row').forEach(r=>r.onclick=()=>loadNamed(r.dataset.preset))}
function renderQuickPresets(){ $('#quickPresetMenu').innerHTML=presets.map(p=>`<button class="quick-preset ${p[0]===state.preset?'active':''}" data-quick-preset="${p[0]}"><b>${p[0]}</b><span>${p[1]}</span></button>`).join('');$$('[data-quick-preset]').forEach(b=>b.onclick=()=>loadNamed(b.dataset.quickPreset)) }
function closeQuickPresets(){const menu=$('#quickPresetMenu');menu.hidden=true;$('#presetToggle').setAttribute('aria-expanded','false')}
function loadNamed(n){const i=presets.findIndex(p=>p[0]===n);state.preset=n;state.presetIndex=i<0?0:i;$('#activePreset').textContent=n;renderQuickPresets();listPresets();closeQuickPresets();toast(`LOADED · ${n}`)}
function stepPreset(offset){const i=(state.presetIndex+offset+presets.length)%presets.length;loadNamed(presets[i][0])}
listPresets();renderQuickPresets();
$('#presetSearch').oninput=e=>listPresets(e.target.value);$$('.category').forEach(b=>b.onclick=()=>{$$('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.presetCategory=b.dataset.category;listPresets();toast(`${b.textContent.trim()} FILTER`)});$('#prevPreset').onclick=()=>stepPreset(-1);$('#nextPreset').onclick=()=>stepPreset(1);$('#presetToggle').onclick=e=>{e.stopPropagation();const menu=$('#quickPresetMenu');menu.hidden=!menu.hidden;$('#presetToggle').setAttribute('aria-expanded',String(!menu.hidden))};document.addEventListener('click',e=>{if(!e.target.closest('.preset-strip'))closeQuickPresets()});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),1800)}
// visualizers
function ctx(id){const el=typeof id==='string'?$(id):id;return [el.getContext('2d'),el.width,el.height]}
function grid(c,w,h){c.strokeStyle='#1c3340';c.lineWidth=1;for(let y=20;y<h;y+=24){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}for(let x=25;x<w;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}}
$$('.wave-canvas').forEach((el,k)=>{const[c,w,h]=ctx(el);grid(c,w,h);for(let layer=5;layer>=0;layer--){c.beginPath();for(let x=0;x<w;x++){let y=h*.53+Math.sin(x*.035+k+layer*.28)*31+Math.sin(x*.09+k)*12;y-=layer*8;y+=x*.012*layer;c.lineTo(x,y)}c.strokeStyle=layer?`rgba(66,141,154,${.16+layer*.05})`:'#5be0dd';c.lineWidth=layer?1:2;c.stroke()}});
$$('.filter-canvas').forEach((el,k)=>{const[c,w,h]=ctx(el);grid(c,w,h);c.beginPath();for(let x=0;x<w;x++){const n=x/w,y=k?h*.55-Math.sin(n*Math.PI*3)*35:h*.3+Math.pow(n,5)*h*.62;c.lineTo(x,y)}c.strokeStyle=k?'#b37aff':'#50dddc';c.lineWidth=3;c.stroke()});
{const[c,w,h]=ctx('#subWave');grid(c,w,h);c.beginPath();for(let x=0;x<w;x++)c.lineTo(x,h/2+Math.sin(x*.055)*20);c.strokeStyle='#50dddc';c.stroke()}{const[c,w,h]=ctx('#noiseWave');grid(c,w,h);c.beginPath();for(let x=0;x<w;x++)c.lineTo(x,h/2+(Math.random()-.5)*32);c.strokeStyle='#b37aff';c.stroke()}
{const[c,w,h]=ctx('#envCanvas');grid(c,w,h);c.beginPath();c.moveTo(0,h-10);c.lineTo(w*.13,20);c.lineTo(w*.34,58);c.lineTo(w*.72,58);c.lineTo(w,h-10);c.strokeStyle='#ff8a38';c.lineWidth=3;c.stroke()}
$$('.lfo-canvas').forEach((el,k)=>{const[c,w,h]=ctx(el);grid(c,w,h);c.beginPath();for(let x=0;x<w;x++){const y=k?h/2+Math.sin(x*.05)*26+Math.sin(x*.12)*8:h/2+Math.asin(Math.sin(x*.045))*24;c.lineTo(x,y)}c.strokeStyle=k?'#b37aff':'#50dddc';c.lineWidth=2;c.stroke()});
// tab and module interactions
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab,.page').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(`#${t.dataset.tab}-page`).classList.add('active')});$$('.engine-modes button,.segmented button').forEach(b=>b.onclick=()=>{const p=b.parentElement;$$('button',p).forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`${b.textContent} SELECTED`)});
$$('.knob-control').forEach(k=>k.ondblclick=()=>toast(`MODULATION TARGET · ${k.dataset.target||$('span',k).textContent}`));$('#addRoute').onclick=()=>{state.routes.push(['MACRO 2','FILTER B · MIX',32]);matrix()};
// Web Audio synthesis MVP: worklet voices with native FX chain
let audio,worklet,master,delay,delayGain,distortion,reverb,reverbGain,audioInit;
const heldNotes=new Set();
function createCompatibilitySynth(context){
  const output=context.createGain(),filter=context.createBiquadFilter(),voices=new Map();let settings=synthSettings;
  filter.type='lowpass';filter.frequency.value=4200;filter.Q.value=2;output.gain.value=.72;filter.connect(output);
  const stopVoice=(note,fast=false)=>{const voice=voices.get(note);if(!voice)return;const now=context.currentTime,release=fast?.015:settings.env.release;voice.amp.gain.cancelScheduledValues(now);voice.amp.gain.setTargetAtTime(0,now,release/5);voice.layers.forEach(({osc})=>osc.stop(now+release));voices.delete(note)};
  const message=data=>{if(data.type==='noteOn'){stopVoice(data.note,true);const now=context.currentTime,amp=context.createGain();amp.gain.setValueAtTime(.0001,now);amp.gain.exponentialRampToValueAtTime((data.velocity||.8)/3,now+settings.env.attack);amp.connect(filter);const layers=settings.osc.map(o=>{const osc=context.createOscillator(),gain=context.createGain();osc.type=o.position<.34?'sine':o.position<.68?'triangle':o.position<.88?'sawtooth':'square';osc.frequency.value=440*Math.pow(2,(data.note-69+o.tune)/12);gain.gain.value=o.level;osc.connect(gain).connect(amp);osc.start();return {osc,gain}});const sub=context.createOscillator(),subGain=context.createGain();sub.type='sine';sub.frequency.value=440*Math.pow(2,(data.note-81)/12);subGain.gain.value=settings.subLevel;sub.connect(subGain).connect(amp);sub.start();layers.push({osc:sub,gain:subGain,sub:true});if(context.createBufferSource){const noise=context.createBufferSource(),noiseGain=context.createGain(),buffer=context.createBuffer(1,Math.max(1,Math.round(context.sampleRate*.5)),context.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=Math.random()*2-1;noise.buffer=buffer;noise.loop=true;noiseGain.gain.value=settings.noiseLevel;noise.connect(noiseGain).connect(amp);noise.start();layers.push({osc:noise,gain:noiseGain,noise:true})}voices.set(data.note,{layers,amp,note:data.note})}if(data.type==='noteOff')stopVoice(data.note);if(data.type==='panic')[...voices.keys()].forEach(note=>stopVoice(note,true));if(data.type==='settings'){settings=data.settings;filter.frequency.setTargetAtTime(120+settings.cutoff*18000,context.currentTime,.02);filter.Q.setTargetAtTime(settings.resonance*18,context.currentTime,.02);voices.forEach(voice=>voice.layers.forEach(({osc,gain,sub,noise},i)=>{if(sub){gain.gain.setTargetAtTime(settings.subLevel,context.currentTime,.02);return}if(noise){gain.gain.setTargetAtTime(settings.noiseLevel,context.currentTime,.02);return}const o=settings.osc[i];osc.type=o.position<.34?'sine':o.position<.68?'triangle':o.position<.88?'sawtooth':'square';osc.frequency.setTargetAtTime(440*Math.pow(2,(voice.note-69+o.tune)/12),context.currentTime,.02);gain.gain.setTargetAtTime(o.level,context.currentTime,.02)}))}};
  return {connect:destination=>{output.connect(destination);return destination},port:{postMessage:message},mode:'compatibility'};
}
async function createSynthNode(context){
  if(context.audioWorklet&&window.AudioWorkletNode){try{await context.audioWorklet.addModule('synth-worklet.js');return new AudioWorkletNode(context,'nocturne-synth',{outputChannelCount:[2]})}catch(error){console.warn('AudioWorklet unavailable; using compatibility synth.',error)}}
  toast('COMPATIBILITY AUDIO MODE');return createCompatibilitySynth(context);
}
async function audioReady(){
  if(worklet){if(audio.state==='suspended')await audio.resume();return worklet}
  if(audioInit)return audioInit;
  audioInit=(async()=>{const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)throw new Error('Web Audio is not supported by this browser');audio=new AudioContextClass();worklet=await createSynthNode(audio);distortion=audio.createWaveShaper();updateDistortionCurve();delay=audio.createDelay(1);delay.delayTime.value=.28;delayGain=audio.createGain();delayGain.gain.value=.19;reverb=audio.createConvolver();const ir=audio.createBuffer(2,audio.sampleRate*1.4,audio.sampleRate);for(let c=0;c<2;c++){const d=ir.getChannelData(c);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3)}reverb.buffer=ir;reverbGain=audio.createGain();reverbGain.gain.value=.16;master=audio.createGain();master.gain.value=+$('#masterVolume').value;worklet.connect(distortion).connect(master);distortion.connect(delay).connect(delayGain).connect(master);distortion.connect(reverb).connect(reverbGain).connect(master);master.connect(audio.destination);sendSynthSettings();if(audio.state==='suspended')await audio.resume();return worklet})().catch(error=>{audioInit=null;audio=null;worklet=null;throw error});
  return audioInit;
}
async function noteOn(note,el){heldNotes.add(note);try{const node=await audioReady();if(!heldNotes.has(note))return;node.port.postMessage({type:'noteOn',note,velocity:.78});state.activeNotes.add(note);if(el)el.classList.add('pressed');$('#voiceCount').textContent=String(state.activeNotes.size).padStart(2,'0')}catch(error){heldNotes.delete(note);console.error(error);toast(`AUDIO ERROR · ${error.message}`)}}
function noteOff(note,el){heldNotes.delete(note);if(worklet)worklet.port.postMessage({type:'noteOff',note});state.activeNotes.delete(note);if(el)el.classList.remove('pressed');$('#voiceCount').textContent=String(state.activeNotes.size).padStart(2,'0')}
const white=[['C',0],['D',2],['E',4],['F',5],['G',7],['A',9],['B',11]],black={C:1,D:1,F:1,G:1,A:1};
function bindPianoKey(key,midi){key.onpointerdown=e=>{e.preventDefault();key.setPointerCapture?.(e.pointerId);noteOn(midi,key)};key.onpointerup=key.onpointercancel=e=>{e.preventDefault();noteOff(midi,key)}}
function keyboard(){const kb=$('#keyboard');kb.innerHTML='';white.forEach(([n,offset],i)=>{const midi=12*(state.octave+1)+offset;const key=document.createElement('div');key.className='key';key.textContent=n+state.octave;bindPianoKey(key,midi);kb.append(key);if(black[n]){const b=document.createElement('div');b.className='key black';b.style.left=`${(i+1)*14.285-2}%`;bindPianoKey(b,midi+1);kb.append(b)}})}keyboard();
$('#octaveDown').onclick=()=>{state.octave=Math.max(1,state.octave-1);$('#octaveLabel').textContent=`OCT ${state.octave}`;keyboard()};$('#octaveUp').onclick=()=>{state.octave=Math.min(7,state.octave+1);$('#octaveLabel').textContent=`OCT ${state.octave}`;keyboard()};$('#masterVolume').oninput=e=>{if(master)master.gain.value=+e.target.value};$('#panicBtn').onclick=()=>{if(worklet)worklet.port.postMessage({type:'panic'});state.activeNotes.clear();heldNotes.clear();$$('.key').forEach(k=>k.classList.remove('pressed'));$('#voiceCount').textContent='00';toast('ALL NOTES STOPPED')};
const keys={a:60,w:61,s:62,e:63,d:64,f:65,t:66,g:67,y:68,h:69,u:70,j:71,k:72};window.onkeydown=e=>{if(/^(INPUT|SELECT|TEXTAREA)$/.test(e.target.tagName))return;if(keys[e.key]&&!e.repeat){e.preventDefault();noteOn(keys[e.key]+(state.octave-4)*12)}};window.onkeyup=e=>{if(keys[e.key])noteOff(keys[e.key]+(state.octave-4)*12)};
$('#savePreset').onclick=()=>{localStorage.setItem('nocturne-preset',JSON.stringify({name:state.preset,routes:state.routes,patch:capturePatch(),version:2}));toast('PRESET SAVED LOCALLY')};$('#exportPreset').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({name:state.preset,routes:state.routes,patch:capturePatch(),version:2},null,2)],{type:'application/json'}));a.download='nocturne-preset.json';a.click();toast('PRESET JSON EXPORTED')};$('#importPreset').onchange=e=>{const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);state.routes=p.routes||state.routes;loadNamed(p.name||'IMPORTED PATCH');if(p.patch)applyPatch(p.patch);matrix();toast('IMPORTED PATCH APPLIED')}catch{toast('INVALID PRESET FILE')}};r.readAsText(e.target.files[0])};
$('#randomize').onclick=()=>{$$('.knob').forEach(k=>k.style.setProperty('--v',Math.round(10+Math.random()*84)));toast('PATCH PARAMETERS RANDOMIZED')};$('#seqPlay').onclick=e=>{state.seq=!state.seq;e.target.textContent=state.seq?'■':'▶';toast(state.seq?'SEQUENCER RUNNING':'SEQUENCER STOPPED')};setInterval(()=>{if(!state.seq)return;$$('.step').forEach(s=>s.style.background='');const s=$$(`.step`)[state.step++%16];s.style.background='#263326'},120);

// Live control layer: knobs, range controls, sound settings, and redrawn visualizers.
const synthSettings={cutoff:.18,resonance:.2,filterMix:.15,subLevel:.12,noiseLevel:.015,noiseColor:.5,lfoRate:1.4,lfoDepth:.02,env:{attack:.03,decay:.22,sustain:.68,release:.45},osc:[{position:.32,tune:0,level:.78,warp:.38},{position:.64,tune:0,level:.56,warp:.51},{position:.47,tune:-12,level:.42,warp:.64}]};
function updateDistortionCurve(amount=2.2){if(!distortion)return;const curve=new Float32Array(512);for(let i=0;i<curve.length;i++){const x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*amount)}distortion.curve=curve}
function sendSynthSettings(){if(worklet)worklet.port.postMessage({type:'settings',settings:synthSettings})}
function knobValue(control){return +(control.dataset.value??control.querySelector('.knob').style.getPropertyValue('--v')??0)}
function setKnob(control,value,announce=false){value=Math.max(0,Math.min(100,Math.round(value)));control.dataset.value=value;control.querySelector('.knob').style.setProperty('--v',value);control.querySelector('b').textContent=value;applyKnob(control,value);if(announce)toast(`${control.querySelector('span').textContent} · ${value}`)}
function applyKnob(control,value){const name=control.querySelector('span').textContent;const osc=control.closest('.osc-card');const filter=control.closest('.filter-card');const fxCard=control.closest('.fx-card');if(osc){const i=$$('.osc-card').indexOf(osc);if(name==='POSITION')synthSettings.osc[i].position=value/100;if(name==='LEVEL')synthSettings.osc[i].level=value/100;if(name==='DETUNE')synthSettings.osc[i].tune=(value-50)/12;drawWave($('.wave-canvas',osc),i)}if(filter&&name==='CUTOFF'){const i=$$('.filter-card').indexOf(filter);if(i===0)synthSettings.cutoff=.01+value/220;drawFilter($('.filter-canvas',filter),i)}if(fxCard){const i=$$('.fx-card').indexOf(fxCard);if(i===0&&name==='DRIVE')updateDistortionCurve(1+value/18);if(i===2&&name==='TIME'&&delay)delay.delayTime.value=.04+value/100;if(i===2&&name==='MIX'&&delayGain)delayGain.gain.value=value/250}sendSynthSettings()}
function bindKnobs(){ $$('.knob-control').forEach(control=>{const knob=$('.knob',control);setKnob(control,knob.style.getPropertyValue('--v'));knob.tabIndex=0;knob.setAttribute('role','slider');knob.setAttribute('aria-label',$('span',control).textContent);let startY,startValue;knob.onpointerdown=e=>{e.preventDefault();startY=e.clientY;startValue=knobValue(control);knob.setPointerCapture?.(e.pointerId);knob.classList.add('editing')};knob.onpointermove=e=>{if(startY===undefined)return;setKnob(control,startValue+(startY-e.clientY)*.75)};knob.onpointerup=knob.onpointercancel=()=>{startY=undefined;knob.classList.remove('editing')};knob.onwheel=e=>{e.preventDefault();setKnob(control,knobValue(control)+(e.deltaY<0?2:-2))};knob.onkeydown=e=>{if(!['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'].includes(e.key))return;e.preventDefault();setKnob(control,knobValue(control)+(['ArrowUp','ArrowRight'].includes(e.key)?1:-1))}})}
function drawWave(el,index){const[c,w,h]=ctx(el);c.clearRect(0,0,w,h);grid(c,w,h);const pos=synthSettings.osc[index].position,warp=+$('input',el.closest('.osc-card').querySelector('.warp'))?.value||0;for(let layer=5;layer>=0;layer--){c.beginPath();for(let x=0;x<w;x++){const p=x/w*Math.PI*6,y=h*.55+Math.sin(p+index+layer*.24)*(18+pos*24)+Math.sin(p*(2+warp/35))*pos*14-layer*7;c.lineTo(x,y)}c.strokeStyle=layer?`rgba(66,141,154,${.15+layer*.05})`:'#5be0dd';c.lineWidth=layer?1:2;c.stroke()}$('.visual-label',el.parentElement).textContent=`FRAME ${String(Math.round(pos*127)+1).padStart(3,'0')} / 128`}
function drawFilter(el,index){const[c,w,h]=ctx(el);c.clearRect(0,0,w,h);grid(c,w,h);const cutoff=index===0?synthSettings.cutoff*2.2:.45;c.beginPath();for(let x=0;x<w;x++){const n=x/w,y=index?h*.55-Math.sin(n*Math.PI*3)*35:h*.25+Math.pow(Math.max(0,n-cutoff)/(1-cutoff),4)*h*.7;c.lineTo(x,y)}c.strokeStyle=index?'#b37aff':'#50dddc';c.lineWidth=3;c.stroke()}
function drawEnvelope(){const[c,w,h]=ctx('#envCanvas');const values=$$('#envSliders input').map(x=>+x.value/100);c.clearRect(0,0,w,h);grid(c,w,h);c.beginPath();c.moveTo(0,h-10);c.lineTo(w*(.04+values[0]*.2),20);c.lineTo(w*(.25+values[1]*.25),h-(25+values[2]*100));c.lineTo(w*.72,h-(25+values[2]*100));c.lineTo(w,h-10-values[3]*8);c.strokeStyle='#ff8a38';c.lineWidth=3;c.stroke()}
function redrawVisuals(){ $$('.wave-canvas').forEach((el,i)=>drawWave(el,i));$$('.filter-canvas').forEach((el,i)=>drawFilter(el,i));drawEnvelope() }
bindKnobs();
$$('input[type=range]').forEach(input=>input.addEventListener('input',()=>{if(input.closest('.env-sliders'))drawEnvelope();if(input.closest('.warp-row')){const card=input.closest('.osc-card');drawWave($('.wave-canvas',card),$$('.osc-card').indexOf(card))}if(input.closest('.matrix-row'))toast('MODULATION AMOUNT UPDATED')}));
$('#randomize').onclick=()=>{$$('.knob-control').forEach(control=>setKnob(control,10+Math.random()*84));redrawVisuals();toast('PATCH PARAMETERS RANDOMIZED')};
redrawVisuals();
let lastScopeFrame=0;
function animateScopes(time=0){requestAnimationFrame(animateScopes);if(time-lastScopeFrame<32)return;lastScopeFrame=time;$$('.lfo-canvas').forEach((el,k)=>{const[c,w,h]=ctx(el);c.clearRect(0,0,w,h);grid(c,w,h);c.beginPath();for(let x=0;x<w;x++){const phase=x*.045+time*.002*(k+1),y=k?h/2+Math.sin(phase)*26+Math.sin(phase*2.4)*8:h/2+Math.asin(Math.sin(phase))*24;c.lineTo(x,y)}c.strokeStyle=k?'#b37aff':'#50dddc';c.lineWidth=2;c.stroke()});const[c,w,h]=ctx('#noiseWave');c.clearRect(0,0,w,h);grid(c,w,h);c.beginPath();for(let x=0;x<w;x++)c.lineTo(x,h/2+(Math.random()-.5)*32);c.strokeStyle='#b37aff';c.stroke()}
requestAnimationFrame(animateScopes);

// Full patch layer: presets and previously decorative sound-design controls now drive audio.
const patchLibrary={
  'SILVER HORIZON':{osc:[[32,78,50,38],[64,56,50,51],[47,42,0,64]],filter:[62,31,18],env:[12,42,68,47],sub:34,noise:20,lfo:22,fx:[68,42,54,42]},
  'NEON SUBWAY':{osc:[[78,92,48,72],[22,38,50,35],[82,62,0,18]],filter:[28,52,8],env:[3,18,82,24],sub:72,noise:8,lfo:10,fx:[82,16,32,18]},
  'CERAMIC BLOOM':{osc:[[18,60,53,85],[88,54,47,76],[52,34,12,92]],filter:[71,22,34],env:[38,66,54,72],sub:8,noise:46,lfo:58,fx:[36,66,74,82]},
  'FRACTAL PLUCK':{osc:[[74,82,50,66],[42,48,62,48],[16,24,38,22]],filter:[54,64,12],env:[1,14,24,18],sub:14,noise:12,lfo:32,fx:[72,24,28,20]},
  'ORBITAL DUST':{osc:[[12,48,50,94],[58,42,55,88],[92,36,45,78]],filter:[43,38,42],env:[54,72,62,88],sub:4,noise:68,lfo:76,fx:[44,78,82,92]},
  'POLAR CHORD':{osc:[[24,66,50,28],[52,60,57,32],[76,52,43,45]],filter:[68,34,22],env:[44,55,78,76],sub:18,noise:18,lfo:42,fx:[28,64,62,78]},
  'VOLTAGE RUNNER':{osc:[[86,86,50,82],[38,54,50,74],[66,38,0,58]],filter:[48,46,10],env:[2,22,48,16],sub:38,noise:16,lfo:88,fx:[76,22,36,28]},
  'EMBER SIGNAL':{osc:[[62,78,50,56],[48,66,53,48],[30,28,0,36]],filter:[58,42,16],env:[8,28,62,34],sub:28,noise:10,lfo:26,fx:[64,38,44,38]},
  'VIOLET MACHINE':{osc:[[92,84,57,96],[70,72,43,88],[48,56,0,76]],filter:[36,72,48],env:[4,34,58,48],sub:32,noise:34,lfo:64,fx:[94,32,46,52]},
  'SUBMERGED':{osc:[[34,76,50,42],[18,44,50,24],[8,68,0,16]],filter:[18,58,6],env:[16,36,88,52],sub:94,noise:6,lfo:8,fx:[48,20,58,44]},
  'GLASS AVIARY':{osc:[[58,74,62,52],[82,54,38,68],[24,30,12,44]],filter:[82,28,18],env:[2,24,42,36],sub:6,noise:22,lfo:48,fx:[34,52,48,62]},
  'CIRRUS FIELD':{osc:[[18,58,50,74],[46,46,55,82],[72,34,43,66]],filter:[64,18,28],env:[62,74,72,96],sub:10,noise:58,lfo:54,fx:[22,74,86,94]}
};

function capturePatch(){const knob=(scope,name)=>knobValue(scopedKnob(scope,name));return {osc:$$('.osc-card').map(card=>[knob(card,'POSITION'),knob(card,'LEVEL'),knob(card,'DETUNE'),+$('.warp input',card).value]),filter:[knob($$('.filter-card')[0],'CUTOFF'),knob($$('.filter-card')[0],'RESONANCE'),knob($$('.filter-card')[0],'MIX')],env:$$('#envSliders input').map(x=>+x.value),sub:+$('.sub-module input[type=range]').value,noise:+$('.noise-module input[type=range]').value,lfo:+$('.lab-controls input[type=range]').value,fx:[knob($$('.fx-card')[0],'DRIVE'),knob($$('.fx-card')[2],'MIX'),knob($$('.fx-card')[2],'TIME'),knob($$('.fx-card')[3],'MIX')]}}
function scopedKnob(scope,name){return $$('.knob-control',scope).find(c=>$('span',c).textContent===name)}
function setRange(input,value){if(input){input.value=value;input.dispatchEvent(new Event('input'))}}
function applyPatch(patch){if(!patch)return;$$('.osc-card').forEach((card,i)=>{const [position,level,detune,warp]=patch.osc[i];setKnob(scopedKnob(card,'POSITION'),position);setKnob(scopedKnob(card,'LEVEL'),level);setKnob(scopedKnob(card,'DETUNE'),detune);setRange($('.warp input',card),warp)});const filter=$$('.filter-card')[0];setKnob(scopedKnob(filter,'CUTOFF'),patch.filter[0]);setKnob(scopedKnob(filter,'RESONANCE'),patch.filter[1]);setKnob(scopedKnob(filter,'MIX'),patch.filter[2]);$$('#envSliders input').forEach((input,i)=>setRange(input,patch.env[i]));setRange($('.sub-module input[type=range]'),patch.sub);setRange($('.noise-module input[type=range]'),patch.noise);setRange($('.lab-controls input[type=range]'),patch.lfo);const fxCards=$$('.fx-card');setKnob(scopedKnob(fxCards[0],'DRIVE'),patch.fx[0]);setKnob(scopedKnob(fxCards[2],'MIX'),patch.fx[1]);setKnob(scopedKnob(fxCards[2],'TIME'),patch.fx[2]);setKnob(scopedKnob(fxCards[3],'MIX'),patch.fx[3]);redrawVisuals();sendSynthSettings()}
function loadNamed(n){const i=presets.findIndex(p=>p[0]===n);state.preset=n;state.presetIndex=i<0?0:i;$('#activePreset').textContent=n;applyPatch(patchLibrary[n]);renderQuickPresets();listPresets();closeQuickPresets();toast(`LOADED · ${n}`)}
function applyKnob(control,value){if(!control)return;const name=$('span',control).textContent,osc=control.closest('.osc-card'),filter=control.closest('.filter-card'),fxCard=control.closest('.fx-card');if(osc){const i=$$('.osc-card').indexOf(osc),o=synthSettings.osc[i];if(name==='POSITION')o.position=value/100;if(name==='LEVEL')o.level=value/100;if(name==='DETUNE')o.tune=(value-50)/4;if(name==='WIDTH')o.width=value/100;drawWave($('.wave-canvas',osc),i)}if(filter){const i=$$('.filter-card').indexOf(filter);if(i===0){if(name==='CUTOFF')synthSettings.cutoff=.01+value/180;if(name==='RESONANCE')synthSettings.resonance=value/120;if(name==='MIX')synthSettings.filterMix=value/100}drawFilter($('.filter-canvas',filter),i)}if(fxCard){const i=$$('.fx-card').indexOf(fxCard);if(i===0&&name==='DRIVE')updateDistortionCurve(1+value/14);if(i===2&&name==='TIME'&&delay)delay.delayTime.value=.04+value/100;if(i===2&&name==='MIX'&&delayGain)delayGain.gain.value=value/180;if(i===3&&name==='MIX'&&reverbGain)reverbGain.gain.value=value/160}sendSynthSettings()}
function syncExtendedControls(){const env=$$('#envSliders input').map(x=>+x.value);synthSettings.env={attack:.005+env[0]/180,decay:.03+env[1]/120,sustain:env[2]/100,release:.04+env[3]/80};synthSettings.subLevel=+$('.sub-module input[type=range]').value/100;synthSettings.noiseLevel=+$('.noise-module input[type=range]').value/350;synthSettings.noiseColor=+$$('.noise-module input[type=range]')[1].value/100;synthSettings.lfoDepth=+$('.lab-controls input[type=range]').value/500;$$('.osc-card').forEach((card,i)=>synthSettings.osc[i].warp=+$('.warp input',card).value/100);sendSynthSettings()}
$$('#envSliders input,.sub-module input[type=range],.noise-module input[type=range],.lab-controls input[type=range],.warp-row input').forEach(input=>input.addEventListener('input',syncExtendedControls));
$$('.matrix-row input').forEach((input,i)=>input.addEventListener('input',()=>{synthSettings.lfoDepth=+input.value/400;sendSynthSettings()}));
syncExtendedControls();
