// Authoritative parameter layer: every visible synth control shares one binding and full-preset path.
const polish={scheduled:[],restoring:false};
const controlValue=control=>control.type==='checkbox'?control.checked:control.tagName==='SELECT'?control.value:+control.value;
const setControl=(control,value)=>{if(!control||value===undefined)return;if(control.type==='checkbox')control.checked=!!value;else control.value=value};
const knobMap=scope=>Object.fromEntries($$('.knob-control',scope).map(control=>[$('span',control).textContent,knobValue(control)]));
const setKnobMap=(scope,values={})=>$$('.knob-control',scope).forEach(control=>{const value=values[$('span',control).textContent];if(value!==undefined)setKnob(control,value)});
const rangeMap=scope=>Object.fromEntries($$('label',scope).map(label=>{const control=$('input,select',label);return control?[label.textContent.trim(),controlValue(control)]:null}).filter(Boolean));
function setRangeMap(scope,values={}){$$('label',scope).forEach(label=>{const control=$('input,select',label),value=values[label.textContent.trim()];if(control&&value!==undefined)setControl(control,value)})}
function fxName(card){return $('h3',card)?.textContent}
function rackModules(){const aliases={COMPRESSOR:'OTT',UTILITY:'MONO BASS'};return $$('.fx-card:not(.inserted-fx)').filter(card=>$('.power',card)?.classList.contains('on')).map(card=>aliases[fxName(card)]||fxName(card)).concat(advanced.fxModules)}
function syncAllControls(){
  if(polish.restoring)return;const oscCards=$$('.osc-card'),filterCards=$$('.filter-card'),sub=$('.sub-module'),noise=$('.noise-module'),labs=$$('.advanced-grid .lab-module');
  synthSettings.oscModes=[];oscCards.forEach((card,index)=>{const values=knobMap(card),warps=$$('.warp',card),osc=synthSettings.osc[index];synthSettings.oscModes[index]=($('.engine-modes .active',card)?.textContent||'WAVETABLE').toLowerCase().replace('multi','multisample');Object.assign(osc,{position:values.POSITION/100,unison:1+Math.round(values.UNISON/17),detune:values.DETUNE/40,width:values.WIDTH/100,level:values.LEVEL/100,pan:values.PAN/100,phase:values.PHASE/100,random:values.RAND/100,warp:+$('input',warps[0]).value/100,warp2:+$('input',warps[1]).value/100,warpMode:$('select',warps[0])?.value||osc.warpMode,warpMode2:$('select',warps[1])?.value||osc.warpMode2})});
  filterCards.forEach((card,index)=>{const values=knobMap(card),filter=synthSettings[index?'filterB':'filterA']||{};Object.assign(filter,{cutoff:.01+values.CUTOFF/180,resonance:values.RESONANCE/120,drive:values.DRIVE/100,mix:values.MIX/100,pan:values.PAN/100});synthSettings[index?'filterB':'filterA']=filter});
  const env=$$('#envSliders input').map(x=>+x.value);synthSettings.env={attack:.005+env[0]/180,decay:.03+env[1]/120,sustain:env[2]/100,release:.04+env[3]/80};
  synthSettings.subLevel=+$('.sub-module input[type=range]').value/100;synthSettings.subShape=$('select',sub).value;synthSettings.subDirect=$('input[type=checkbox]',sub).checked;
  synthSettings.noiseLevel=+$$('input[type=range]',noise)[0].value/350;synthSettings.noiseColor=+$$('input[type=range]',noise)[1].value/100;synthSettings.noiseKey=$('input[type=checkbox]',noise).checked;
  const granular=$$('input[type=range]',labs[0]).slice(0,4).map(x=>+x.value/100),spectral=$$('input[type=range]',labs[1]).map(x=>+x.value/100);Object.assign(synthSettings.granular,{size:granular[0],density:granular[1],spray:granular[2],texture:granular[3]});$$('[data-grain]').forEach(control=>synthSettings.granular[control.dataset.grain]=control.type==='checkbox'?control.checked:+control.value/100);Object.assign(synthSettings.spectral,{blur:spectral[0],shift:spectral[1],formant:spectral[2],stretch:spectral[3]});
  synthSettings.macros=$$('.macro .knob').map(knob=>knobValue(knob.closest('.knob-control'))/100);synthSettings.fxParams=Object.fromEntries($$('.fx-card:not(.inserted-fx)').map(card=>[fxName(card),Object.fromEntries(Object.entries(knobMap(card)).map(([key,value])=>[key.toLowerCase(),value/100]))]));synthSettings.fxModules=rackModules();
  synthSettings.masterVolume=+$('#masterVolume').value;synthSettings.sequencer={tempo:+$('#tempo').value,swing:+$('.seq-toolbar input[type=range]').value,scale:$('.seq-toolbar select').value,mode:$('#patternMode')?.value||'CLIP'};sendSynthSettings();
}
function fullPatch(){
  const labs=$$('.advanced-grid .lab-module');return {format:'nocturne-patch',version:3,name:state.preset,routes:state.routes.map(routeObject),osc:$$('.osc-card').map(card=>({knobs:knobMap(card),warps:$$('.warp',card).map(warp=>({amount:+$('input',warp).value,mode:$('select',warp)?.value})),mode:$('.engine-modes .active',card)?.textContent||'WAVETABLE'})),filters:$$('.filter-card').map(card=>knobMap(card)),filterRouting:synthSettings.filterRouting,oscRoutes:[...synthSettings.oscRoutes],sub:rangeMap($('.sub-module')),noise:rangeMap($('.noise-module')),env:rangeMap($('#envSliders')),granular:rangeMap(labs[0]),spectral:rangeMap(labs[1]),macros:$$('.macro').map(control=>knobValue(control)),fx:$$('.fx-card:not(.inserted-fx)').map(card=>({name:fxName(card),enabled:$('.power',card).classList.contains('on'),knobs:knobMap(card)})),fxModules:[...advanced.fxModules],fxBus:synthSettings.fxBus||'BUS A',source:{mode:synthSettings.source?.mode||'wavetable',name:synthSettings.source?.name||'Factory table'},sampler:{...synthSettings.sampler},quality:{polyphony:+$('#polyphony').value,oversampling:+$('#oversample').value},sequencer:{tempo:+$('#tempo').value,swing:+$('.seq-toolbar input[type=range]').value,scale:$('.seq-toolbar select').value,mode:$('#patternMode')?.value||'CLIP',steps:pro.steps.map(step=>({...step}))},masterVolume:+$('#masterVolume').value,partials:[...(studio.partials||[])]};
}
function restoreFullPatch(patch){
  polish.restoring=true;try{state.routes=(patch.routes||state.routes).map(routeObject);$$('.osc-card').forEach((card,index)=>{const saved=patch.osc?.[index];if(!saved)return;setKnobMap(card,saved.knobs);$$('.warp',card).forEach((warp,warpIndex)=>{const value=saved.warps?.[warpIndex];if(value){setControl($('input',warp),value.amount);setControl($('select',warp),value.mode)}});$$('.engine-modes button',card).forEach(button=>button.classList.toggle('active',button.textContent===(saved.mode||'WAVETABLE')))});$$('.filter-card').forEach((card,index)=>setKnobMap(card,patch.filters?.[index]));setRangeMap($('.sub-module'),patch.sub);setRangeMap($('.noise-module'),patch.noise);setRangeMap($('#envSliders'),patch.env);const labs=$$('.advanced-grid .lab-module');setRangeMap(labs[0],patch.granular);setRangeMap(labs[1],patch.spectral);$$('.macro').forEach((control,index)=>patch.macros?.[index]!==undefined&&setKnob(control,patch.macros[index]));$$('.fx-card:not(.inserted-fx)').forEach(card=>{const saved=patch.fx?.find(item=>item.name===fxName(card));if(saved){$('.power',card).classList.toggle('on',saved.enabled);setKnobMap(card,saved.knobs)}});advanced.fxModules=[];$$('.inserted-fx').forEach(card=>card.remove());(patch.fxModules||[]).forEach(insertFx);synthSettings.filterRouting=patch.filterRouting||'PARALLEL';synthSettings.fxBus=patch.fxBus||'BUS A';synthSettings.source={...(synthSettings.source||{}),...(patch.source||{})};$$('.fx-toolbar .segmented button').forEach(button=>button.classList.toggle('active',button.textContent===synthSettings.fxBus));$$('#filterRouting button').forEach(button=>button.classList.toggle('active',button.textContent===synthSettings.filterRouting));synthSettings.oscRoutes=[...(patch.oscRoutes||synthSettings.oscRoutes)];renderOscRouting();Object.assign(synthSettings.sampler,patch.sampler||{});setControl($('#polyphony'),patch.quality?.polyphony);setControl($('#oversample'),patch.quality?.oversampling);setControl($('#tempo'),patch.sequencer?.tempo);setControl($('.seq-toolbar input[type=range]'),patch.sequencer?.swing);setControl($('.seq-toolbar select'),patch.sequencer?.scale);setControl($('#patternMode'),patch.sequencer?.mode);if(patch.sequencer?.steps)pro.steps=patch.sequencer.steps.map(step=>({...step}));setControl($('#masterVolume'),patch.masterVolume);if(patch.partials){studio.partials=[...patch.partials];synthSettings.spectral.partials=[...patch.partials]}}finally{polish.restoring=false}matrix();renderClip();drawPartials();if(master)master.gain.value=+$('#masterVolume').value;syncAllControls();publishAdvanced()}
function legacyPersonality(patch){const seed=[...state.preset].reduce((n,char)=>n+char.charCodeAt(0),0),value=(offset,min=8,max=92)=>min+(seed*(offset+7)%997)%(max-min+1);$$('.osc-card').forEach((card,index)=>{setKnob(scopedKnob(card,'UNISON'),value(index+1,18,88));setKnob(scopedKnob(card,'WIDTH'),value(index+3));setKnob(scopedKnob(card,'PAN'),value(index+5,32,68));setKnob(scopedKnob(card,'PHASE'),value(index+7));setKnob(scopedKnob(card,'RAND'),value(index+9));setControl($$('.warp input',card)[1],value(index+11))});setKnobMap($$('.filter-card')[1],{CUTOFF:value(13),RESONANCE:value(15),DRIVE:value(17),MIX:value(19),PAN:value(21,35,65)});$$('.macro').forEach((control,index)=>setKnob(control,value(index+23)));setControl($('.sub-module select'),['SINE','TRIANGLE','SQUARE'][seed%3]);setControl($('.sub-module input[type=checkbox]'),seed%2);setControl($('.noise-module input[type=checkbox]'),seed%3===0)}
const legacyApplyPatch=applyPatch;capturePatch=fullPatch;applyPatch=function(patch){if(patch?.format==='nocturne-patch'&&patch.version>=3)return restoreFullPatch(patch);polish.restoring=true;try{legacyApplyPatch(patch);legacyPersonality(patch)}finally{polish.restoring=false}syncAllControls();publishAdvanced()};
const integratedApplyKnob=applyKnob;applyKnob=function(control,value){integratedApplyKnob(control,value);syncAllControls()};
$$('.warp-row input,.warp-row select,.compact-controls input,.compact-controls select,#envSliders input,.advanced-grid input,.advanced-grid select,.pro-controls input,.pro-controls select,#tempo,.seq-toolbar input,.seq-toolbar select').forEach(control=>control.addEventListener('input',syncAllControls));
$$('.fx-card:not(.inserted-fx) .power').forEach(power=>power.onclick=()=>{power.classList.toggle('on');syncAllControls();toast(`${fxName(power.closest('.fx-card'))} · ${power.classList.contains('on')?'ON':'OFF'}`)});
$$('.fx-toolbar .segmented button').forEach(button=>button.onclick=()=>{$$('.fx-toolbar .segmented button').forEach(b=>b.classList.toggle('active',b===button));synthSettings.fxBus=button.textContent;toast(`FX ROUTE · ${button.textContent}`)});
function downloadJson(payload,name){const link=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#savePreset').onclick=()=>{localStorage.setItem('nocturne-preset',JSON.stringify(fullPatch()));toast('FULL PRESET SAVED LOCALLY')};$('#exportPreset').onclick=()=>{downloadJson(fullPatch(),'nocturne-preset.nsp.json');toast('FULL PRESET EXPORTED')};$('#importPreset').onchange=e=>{const reader=new FileReader();reader.onload=()=>{try{const patch=JSON.parse(reader.result);state.preset=patch.name||'IMPORTED PATCH';$('#activePreset').textContent=state.preset;applyPatch(patch);toast('FULL PRESET IMPORTED')}catch(error){console.error(error);toast('INVALID PRESET FILE')}};reader.readAsText(e.target.files[0])};
$('#exportPack').onclick=()=>{downloadJson({format:'nocturne-pack',version:3,author:studio.author,patches:[fullPatch()]},'nocturne-preset-pack.nsp.json');toast('FULL PRESET PACK EXPORTED')};
function clearScheduled(){polish.scheduled.splice(0).forEach(id=>clearTimeout(id))}const integratedStop=stopSequencer;stopSequencer=function(){clearScheduled();integratedStop()};sequencerTick=function(){const step=state.step++%16,config=pro.steps[step],note=config.note??pattern[step];$$('.step').forEach((el,index)=>el.classList.toggle('playing',index===step));if(advanced.sequenceNote!==null)noteOff(advanced.sequenceNote);clearScheduled();advanced.sequenceNote=null;if(note==null||Math.random()*100>config.probability)return;advanced.sequenceNote=note;const duration=60000/(+$('#tempo').value||124)/4,ratchets=Math.max(1,+config.ratchet||1),slice=duration/ratchets,gate=Math.max(.05,config.gate/100);for(let i=0;i<ratchets;i++){polish.scheduled.push(setTimeout(()=>noteOn(note,null,config.velocity/100),i*slice));polish.scheduled.push(setTimeout(()=>noteOff(note),i*slice+slice*gate))}};
syncAllControls();
