const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
const lerp=(a,b,t)=>a+(b-a)*t;
const read=(buffer,index)=>{if(!buffer?.length)return 0;const wrapped=((index%buffer.length)+buffer.length)%buffer.length,a=Math.floor(wrapped),b=(a+1)%buffer.length;return lerp(buffer[a],buffer[b],wrapped-a)};
class NocturneVoice {
  constructor(note,velocity,settings,rate){this.note=note;this.velocity=velocity;this.settings=settings;this.rate=rate;this.freq=440*Math.pow(2,(note-69)/12);this.age=0;this.released=false;this.releaseAt=0;this.seed=(note*9973)%2147483647;this.layers=[];this.samplePosition=0;this.grainClock=0;this.grains=[];this.filters={A:{low:[0,0],band:[0,0]},B:{low:[0,0],band:[0,0]}}}
  random(){this.seed=this.seed*16807%2147483647;return this.seed/2147483647}
  envelope(){const s=this.settings.env,t=this.age/this.rate;if(this.released)return Math.max(0,this.releaseLevel*(1-(this.age-this.releaseAt)/(this.rate*s.release)));if(t<s.attack)return t/s.attack;if(t<s.attack+s.decay)return 1-(1-s.sustain)*(t-s.attack)/s.decay;return s.sustain}
  sourceValue(name,lfo1,lfo2,env){if(name==='LFO 1')return lfo1;if(name==='LFO 2')return lfo2;if(name==='ENV 1'||name==='ENV 2')return env;if(name?.startsWith('MACRO'))return (this.settings.macros?.[+name.split(' ')[1]-1]||0)-.5;return 0}
  modulations(lfo1,lfo2,env){const out={position:[0,0,0],warp:[0,0,0],cutA:0,cutB:0,drive:0};for(const route of this.settings.routes||[]){const value=this.sourceValue(route.source,lfo1,lfo2,env)*(route.amount||0)/100,d=route.destination||'';for(let i=0;i<3;i++){const id='ABC'[i];if(d.includes(`OSC ${id} · WT POS`))out.position[i]+=value;if(d.includes(`OSC ${id} · WARP`))out.warp[i]+=value}if(d.includes('FILTER A · CUTOFF'))out.cutA+=value;if(d.includes('FILTER B · CUTOFF'))out.cutB+=value;if(d.includes('FX A · DRIVE'))out.drive+=value}return out}
  builtin(phase,position,warp){const p=((phase+Math.sin(phase*Math.PI*2)*warp*.12)%1+1)%1,sine=Math.sin(p*Math.PI*2),saw=p*2-1,square=p<.5?1:-1,tri=1-4*Math.abs(p-.5);if(position<.34)return lerp(sine,tri,position/.34);if(position<.68)return lerp(tri,saw,(position-.34)/.34);return lerp(saw,square,(position-.68)/.32)}
  wavetable(phase,position,warp){const custom=this.settings.source?.table;if(!custom?.length)return this.builtin(phase,position,warp);return read(custom,phase*custom.length)}
  harmonic(phase,spectral){let sum=0,norm=0;for(let harmonic=1;harmonic<=12;harmonic++){const shifted=harmonic+(spectral.shift-.5)*4,stretched=Math.pow(Math.max(.25,shifted),1+(spectral.stretch-.5)*.45),formant=1+(spectral.formant-.5)*Math.cos(harmonic*.72),blur=1-spectral.blur*harmonic/18,amp=Math.max(0,formant*blur)/harmonic;sum+=Math.sin(phase*Math.PI*2*stretched)*amp;norm+=amp}return norm?sum/norm:0}
  oscillator(index,osc,mods){const voices=Math.max(1,Math.min(7,Math.round(osc.unison||1))),position=clamp(osc.position+mods.position[index]),warp=clamp(osc.warp+mods.warp[index]);if(!this.layers[index])this.layers[index]=Array.from({length:voices},(_,voice)=>({phase:(osc.phase||0)+(this.random()-.5)*(osc.random||0),voice}));while(this.layers[index].length<voices)this.layers[index].push({phase:this.random(),voice:this.layers[index].length});let left=0,right=0;for(const layer of this.layers[index].slice(0,voices)){const spread=voices===1?0:(layer.voice/(voices-1)-.5)*2,ratio=Math.pow(2,((osc.tune||0)+spread*(osc.detune||0))/12);layer.phase+=this.freq*ratio/this.rate;const mode=this.settings.oscModes?.[index]||'wavetable',value=mode==='spectral'?this.harmonic(layer.phase,this.settings.spectral):this.wavetable(layer.phase,position,warp),pan=clamp((osc.pan??.5)+spread*(osc.width??.5)*.48);left+=value*Math.sqrt(1-pan);right+=value*Math.sqrt(pan)}return [left/voices*osc.level,right/voices*osc.level]}
  sampleSource(){const source=this.settings.source||{},mapped=source.mode==='multisample'&&source.multisamples?.length?[...source.multisamples].sort((a,b)=>Math.abs(this.note-a.root)-Math.abs(this.note-b.root))[0]:source,buffer=mapped.buffer;if(!buffer?.length)return [0,0];const root=mapped.root??60,step=Math.pow(2,(this.note-root)/12),value=this.samplePosition<buffer.length?read(buffer,this.samplePosition):0;this.samplePosition+=step;return [value,value]}
  granularSource(){const source=this.settings.source||{},buffer=source.buffer||source.multisamples?.[0]?.buffer;if(!buffer?.length)return [0,0];const g=this.settings.granular||{},density=3+g.density*36,size=Math.max(48,Math.round((.015+g.size*.22)*this.rate));this.grainClock-=1;if(this.grainClock<=0){this.grainClock=this.rate/density;this.grains.push({position:this.random()*Math.max(1,buffer.length-size),age:0,size,pan:this.random(),step:Math.pow(2,((g.pitch||.5)-.5)*2)})}let left=0,right=0;this.grains=this.grains.filter(grain=>{if(grain.age>=grain.size)return false;const window=.5-.5*Math.cos(Math.PI*2*grain.age/grain.size),value=read(buffer,grain.position+grain.age*grain.step)*window;left+=value*Math.sqrt(1-grain.pan);right+=value*Math.sqrt(grain.pan);grain.age++;return true});return [left*.45,right*.45]}
  filter(input,cutoff,resonance,id){const state=this.filters[id],c=clamp(cutoff,.004,.48);return input.map((value,channel)=>{state.low[channel]+=c*state.band[channel];state.band[channel]+=c*(value-state.low[channel]-resonance*state.band[channel]);return state.low[channel]})}
  next(){this.age++;const env=this.envelope();if(env<=0)return null;const s=this.settings,t=this.age/this.rate,lfo1=Math.sin(t*Math.PI*2*(s.lfoRate||1.4)),lfo2=Math.asin(Math.sin(t*Math.PI*2*(s.lfo2Rate||.65)))*2/Math.PI,mods=this.modulations(lfo1,lfo2,env),buses={A:[0,0],B:[0,0],MASTER:[0,0]};s.osc.forEach((osc,index)=>{const mode=s.oscModes?.[index]||'wavetable',signal=mode==='sample'||mode==='multi'?this.sampleSource():mode==='grain'?this.granularSource():this.oscillator(index,osc,mods),route=s.oscRoutes?.[index]||'A';signal.forEach((value,c)=>buses[route][c]+=value)});const sub=Math.sin(t*Math.PI*2*this.freq*.5)*s.subLevel,noise=(this.random()*2-1)*s.noiseLevel;buses.A[0]+=sub+noise;buses.A[1]+=sub+noise;const a=this.filter(buses.A,(s.filterA?.cutoff??.18)+mods.cutA*.2,s.filterA?.resonance??.2,'A'),b=this.filter(buses.B,(s.filterB?.cutoff??.24)+mods.cutB*.2,s.filterB?.resonance??.3,'B');let filtered;if(s.filterRouting==='SERIES A › B')filtered=this.filter(a,s.filterB?.cutoff??.24,s.filterB?.resonance??.3,'B');else if(s.filterRouting==='SERIES B › A')filtered=this.filter(b,s.filterA?.cutoff??.18,s.filterA?.resonance??.2,'A');else filtered=[(a[0]+b[0]),(a[1]+b[1])];return filtered.map((value,c)=>(value+buses.MASTER[c])*this.velocity*env)}
  release(){if(!this.released){this.releaseLevel=this.envelope();this.released=true;this.releaseAt=this.age}}
}
class NocturneProcessor extends AudioWorkletProcessor {
  constructor(){super();this.voices=[];this.fxPhase=0;this.delay=[new Float32Array(sampleRate),new Float32Array(sampleRate)];this.delayIndex=0;this.low=[0,0];this.settings={filterRouting:'PARALLEL',filterA:{cutoff:.18,resonance:.2,mix:.15},filterB:{cutoff:.24,resonance:.3,mix:.42},oscRoutes:['A','B','MASTER'],oscModes:['wavetable','wavetable','wavetable'],subLevel:.12,noiseLevel:.015,lfoRate:1.4,lfo2Rate:.65,env:{attack:.03,decay:.22,sustain:.68,release:.45},granular:{size:.42,density:.66,spray:.28,texture:.57},spectral:{blur:.36,shift:.51,formant:.63,stretch:.21},routes:[],fxModules:[],osc:[{position:.18,tune:0,level:.8,warp:.2},{position:.52,tune:0,level:.6,warp:.1},{position:.82,tune:-12,level:.44,warp:.1}]};this.port.onmessage=e=>this.message(e.data)}
  message(data){if(data.type==='noteOn')this.voices.push(new NocturneVoice(data.note,data.velocity||.8,this.settings,sampleRate));if(data.type==='noteOff')this.voices.forEach(v=>{if(v.note===data.note)v.release()});if(data.type==='panic')this.voices=[];if(data.type==='settings'){this.settings=data.settings;this.voices.forEach(v=>v.settings=data.settings)}if(data.type==='source')this.settings.source={...(this.settings.source||{}),...data.source}}
  effects(stereo){for(const name of this.settings.fxModules||[]){this.fxPhase+=1/sampleRate;if(name==='FLANGER')stereo=stereo.map((x,c)=>x+read(this.delay[c],this.delayIndex-(120+Math.sin(this.fxPhase*3)*90))*.34);if(name==='PHASER')stereo=stereo.map((x,c)=>{this.low[c]+=.08*(x-this.low[c]);return x-this.low[c]*.72});if(name==='CONVOLUTION')stereo=stereo.map((x,c)=>x+read(this.delay[c],this.delayIndex-4200)*.28+read(this.delay[c],this.delayIndex-7800)*.16);if(name==='FILTER FX')stereo=stereo.map((x,c)=>{this.low[c]+=.12*(x-this.low[c]);return this.low[c]});if(name==='STEREO WIDTH'){const mid=(stereo[0]+stereo[1])*.5,side=(stereo[0]-stereo[1])*.68;stereo=[mid+side,mid-side]}if(name==='MID / SIDE')stereo=[stereo[0]*1.08,stereo[1]*.92];if(name==='MULTIBAND SPLIT')stereo=stereo.map(x=>Math.tanh(x*1.24));if(name==='MONO BASS'){const mid=(stereo[0]+stereo[1])*.5;stereo=[lerp(stereo[0],mid,.34),lerp(stereo[1],mid,.34)]}}stereo.forEach((x,c)=>this.delay[c][this.delayIndex]=x);this.delayIndex=(this.delayIndex+1)%this.delay[0].length;return stereo}
  process(_,outputs){const out=outputs[0];out.forEach(c=>c.fill(0));for(let i=0;i<out[0].length;i++){let stereo=[0,0];this.voices=this.voices.filter(v=>{const next=v.next();if(next===null)return false;stereo[0]+=next[0];stereo[1]+=next[1];return true});stereo=this.effects(stereo).map(x=>Math.tanh(x*1.45));out.forEach((channel,c)=>channel[i]=stereo[c]??stereo[0])}return true}
}
registerProcessor('nocturne-synth',NocturneProcessor);
