const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
const lerp=(a,b,t)=>a+(b-a)*t;
const read=(buffer,index)=>{if(!buffer?.length)return 0;const wrapped=((index%buffer.length)+buffer.length)%buffer.length,a=Math.floor(wrapped),b=(a+1)%buffer.length;return lerp(buffer[a],buffer[b],wrapped-a)};
const polyBlep=(t,dt)=>{if(t<dt){t/=dt;return t+t-t*t-1}if(t>1-dt){t=(t-1)/dt;return t*t+t+t+1}return 0};
const bandRead=(buffer,index,step=1)=>{const taps=Math.max(1,Math.min(8,Math.ceil(step)));let sum=0;for(let i=0;i<taps;i++)sum+=read(buffer,index+(i-(taps-1)/2)*step/taps);return sum/taps};
class NocturneVoice {
  constructor(note,velocity,settings,rate){this.note=note;this.velocity=velocity;this.settings=settings;this.rate=rate;this.freq=440*Math.pow(2,(note-69)/12);this.age=0;this.released=false;this.releaseAt=0;this.seed=(note*9973)%2147483647;this.layers=[];this.samplePosition=0;this.noiseState=0;this.grainClock=0;this.grains=[];this.filters={A:{low:[0,0],band:[0,0]},B:{low:[0,0],band:[0,0]}}}
  random(){this.seed=this.seed*16807%2147483647;return this.seed/2147483647}
  envelope(){const s=this.settings.env,t=this.age/this.rate;if(this.released)return Math.max(0,this.releaseLevel*(1-(this.age-this.releaseAt)/(this.rate*s.release)));if(t<s.attack)return t/s.attack;if(t<s.attack+s.decay)return 1-(1-s.sustain)*(t-s.attack)/s.decay;return s.sustain}
  sourceValue(name,lfo1,lfo2,env){if(name==='LFO 1')return lfo1;if(name==='LFO 2')return lfo2;if(name==='ENV 1'||name==='ENV 2')return env;if(name==='VELOCITY')return this.velocity;if(name==='KEYTRACK'||name==='NOTE')return clamp((this.note-36)/60);if(name==='RANDOM')return this.random()*2-1;if(name?.startsWith('MACRO'))return (this.settings.macros?.[+name.split(' ')[1]-1]||0)-.5;return 0}
  modulations(lfo1,lfo2,env){const out={position:[0,0,0],warp:[0,0,0],level:[0,0,0],pan:[0,0,0],cutA:0,cutB:0,resA:0,resB:0,mixA:0,mixB:0,drive:0};for(const route of this.settings.routes||[]){const value=this.sourceValue(route.source,lfo1,lfo2,env)*(route.amount||0)/100,d=route.destination||'';for(let i=0;i<3;i++){const id='ABC'[i];if(d.includes(`OSC ${id} · WT POS`))out.position[i]+=value;if(d.includes(`OSC ${id} · WARP`))out.warp[i]+=value;if(d.includes(`OSC ${id} · LEVEL`))out.level[i]+=value;if(d.includes(`OSC ${id} · PAN`))out.pan[i]+=value}if(d.includes('FILTER A · CUTOFF'))out.cutA+=value;if(d.includes('FILTER B · CUTOFF'))out.cutB+=value;if(d.includes('FILTER A · RESONANCE'))out.resA+=value;if(d.includes('FILTER B · RESONANCE'))out.resB+=value;if(d.includes('FILTER A · MIX'))out.mixA+=value;if(d.includes('FILTER B · MIX'))out.mixB+=value;if(d.includes('FX A · DRIVE'))out.drive+=value}return out}
  warp(phase,amount,mode='BEND'){let p=((phase%1)+1)%1;if(mode==='SYNC')p=(p*(1+Math.round(amount*5)))%1;if(mode==='MIRROR')p=1-Math.abs(1-(p*2%2));if(mode==='REMAP')p=Math.pow(p,.35+amount*2.4);if(mode==='FM')p+=Math.sin(p*Math.PI*2)*amount*.2;if(mode==='FOLD')p=Math.abs(((p*(1+amount*4))%2)-1);if(mode==='PWM')p=clamp(p+(amount-.5)*.45);return ((p%1)+1)%1}
  builtin(phase,position,warp,mode,dt=.01){const p=this.warp(phase,warp,mode),sine=Math.sin(p*Math.PI*2),saw=p*2-1-polyBlep(p,dt),square=(p<.5?1:-1)+polyBlep(p,dt)-polyBlep((p+.5)%1,dt),tri=1-4*Math.abs(p-.5),value=position<.34?lerp(sine,tri,position/.34):position<.68?lerp(tri,saw,(position-.34)/.34):lerp(saw,square,(position-.68)/.32);return mode==='AM'?value*(.45+.55*Math.sin(phase*Math.PI*2*(1+warp*6))):value}
  wavetable(phase,position,warp,mode,dt=.01){const frames=this.settings.source?.frames,p=this.warp(phase,warp,mode);if(frames?.length){const frame=clamp(position)*(frames.length-1),a=Math.floor(frame),b=Math.min(frames.length-1,a+1),mix=frame-a,step=Math.max(1,dt*frames[a].length);return lerp(bandRead(frames[a],p*frames[a].length,step),bandRead(frames[b],p*frames[b].length,step),mix)}const custom=this.settings.source?.table;if(!custom?.length)return this.builtin(phase,position,warp,mode,dt);return bandRead(custom,p*custom.length,Math.max(1,dt*custom.length))}
  harmonic(phase,spectral){let sum=0,norm=0;const partials=spectral.partials||[];for(let harmonic=1;harmonic<=32;harmonic++){const shifted=harmonic+(spectral.shift-.5)*8,stretched=Math.pow(Math.max(.25,shifted),1+(spectral.stretch-.5)*.45),formant=1+(spectral.formant-.5)*Math.cos(harmonic*.72),blur=Math.max(0,1-spectral.blur*harmonic/38),source=partials.length?(partials[harmonic-1]||0):1/harmonic,amp=Math.max(0,source*formant*blur);sum+=Math.sin(phase*Math.PI*2*stretched)*amp;norm+=amp}return norm?sum/norm:0}
  oscillator(index,osc,mods){const voices=Math.max(1,Math.min(7,Math.round(osc.unison||1))),position=clamp(osc.position+mods.position[index]),warp=clamp(osc.warp+mods.warp[index]),warp2=clamp(osc.warp2||0),level=clamp(osc.level+mods.level[index]);if(!this.layers[index])this.layers[index]=Array.from({length:voices},(_,voice)=>({phase:(osc.phase||0)+(this.random()-.5)*(osc.random||0),voice}));while(this.layers[index].length<voices)this.layers[index].push({phase:this.random(),voice:this.layers[index].length});let left=0,right=0;for(const layer of this.layers[index].slice(0,voices)){const spread=voices===1?0:(layer.voice/(voices-1)-.5)*2,ratio=Math.pow(2,((osc.tune||0)+spread*(osc.detune||0))/12);layer.phase+=this.freq*ratio/this.rate;const phase=this.warp(this.warp(layer.phase,warp,osc.warpMode),warp2,osc.warpMode2),mode=this.settings.oscModes?.[index]||'wavetable',value=mode==='spectral'?this.harmonic(phase,this.settings.spectral):this.wavetable(phase,position,0,'BEND',this.freq*ratio/this.rate),pan=clamp((osc.pan??.5)+mods.pan[index]+spread*(osc.width??.5)*.48);left+=value*Math.sqrt(1-pan);right+=value*Math.sqrt(pan)}return [left/voices*level,right/voices*level]}
  sampleSource(){const source=this.settings.source||{},zone=(this.settings.sfzZones||[]).find(z=>this.note>=z.lokey&&this.note<=z.hikey&&this.velocity*127>=z.lovel&&this.velocity*127<=z.hivel),mapped=zone||(source.mode==='multisample'&&source.multisamples?.length?[...source.multisamples].sort((a,b)=>Math.abs(this.note-a.root)-Math.abs(this.note-b.root))[0]:source),buffer=mapped.buffer,s=this.settings.sampler||{};if(!buffer?.length)return [0,0];const start=zone?.loopStart||clamp(s.start||0)*buffer.length,end=Math.max(start+2,zone?.loopEnd||clamp(s.end??1)*buffer.length),root=mapped.root??60,step=Math.pow(2,(this.note-root)/12)*(s.stretch||1)*(s.reverse?-1:1),loop=zone?.loop&&zone.loop!=='no_loop'?'FORWARD':s.loop,crossfade=zone?.crossfade||128;if(!this.sampleStarted){this.samplePosition=s.reverse?end-1:start;this.sampleStarted=true}let position=this.samplePosition;if(position<start||position>=end){if(loop==='FORWARD')position=s.reverse?end-1:start;else if(loop==='PING PONG'){this.sampleDirection=(this.sampleDirection||1)*-1;position=clamp(position,start,end-1)}else return [0,0]}const slices=Math.max(1,s.slices||1),sliceSize=(end-start)/slices;if(slices>1)position=start+(position-start)%sliceSize;let value=read(buffer,position);if(loop==='FORWARD'&&!s.reverse&&position>end-crossfade)value=lerp(value,read(buffer,start+(position-(end-crossfade))),clamp((position-(end-crossfade))/crossfade));this.samplePosition=position+step*(this.sampleDirection||1);return [value,value]}

  granularSource(){const source=this.settings.source||{},buffer=source.buffer||source.multisamples?.[0]?.buffer;if(!buffer?.length)return [0,0];const g=this.settings.granular||{},density=3+g.density*52,size=Math.max(48,Math.round((.012+g.size*.28)*this.rate)),center=clamp(g.position??.5)*buffer.length,range=(g.random??g.spray??.2)*buffer.length*.7;this.grainClock-=1;if(this.grainClock<=0&&!g.freeze){this.grainClock=this.rate/density;this.grains.push({position:clamp(center+(this.random()-.5)*range,0,Math.max(1,buffer.length-size)),age:0,size,pan:clamp(.5+(this.random()-.5)*(g.spread??1)),step:Math.pow(2,(((g.pitch??.5)-.5)*24)/12)})}if(g.freeze&&this.grains.length===0)this.grains.push({position:center,age:0,size,pan:.5,step:1,freeze:true});let left=0,right=0;this.grains=this.grains.filter(grain=>{if(grain.age>=grain.size){if(!grain.freeze)return false;grain.age=0}const window=.5-.5*Math.cos(Math.PI*2*grain.age/grain.size),value=read(buffer,grain.position+grain.age*grain.step)*window;left+=value*Math.sqrt(1-grain.pan);right+=value*Math.sqrt(grain.pan);grain.age++;return true});return [left*.45,right*.45]}

  filter(input,cutoff,resonance,id,mix=1,drive=0,pan=.5){const state=this.filters[id],c=clamp(cutoff,.004,.48),wet=clamp(mix),gain=1+clamp(drive)*4,position=clamp(pan);return input.map((value,channel)=>{const driven=Math.tanh(value*gain);state.low[channel]+=c*state.band[channel];state.band[channel]+=c*(driven-state.low[channel]-clamp(resonance,0,1.4)*state.band[channel]);return lerp(value,state.low[channel],wet)*(channel?Math.sqrt(position*2):Math.sqrt((1-position)*2))})}
  next(){this.age++;const env=this.envelope();if(env<=0)return null;const s=this.settings,t=this.age/this.rate,lfo1=Math.sin(t*Math.PI*2*(s.lfoRate||1.4)),lfo2=Math.asin(Math.sin(t*Math.PI*2*(s.lfo2Rate||.65)))*2/Math.PI,mods=this.modulations(lfo1,lfo2,env),buses={A:[0,0],B:[0,0],MASTER:[0,0]};s.osc.forEach((osc,index)=>{const mode=s.oscModes?.[index]||'wavetable',signal=mode==='sample'||mode==='multi'||mode==='multisample'?this.sampleSource():mode==='grain'?this.granularSource():this.oscillator(index,osc,mods),route=s.oscRoutes?.[index]||'A';signal.forEach((value,c)=>buses[route][c]+=value)});const subPhase=t*Math.PI*2*this.freq*.5,subShape=s.subShape||'SINE',sub=(subShape==='SQUARE'?(Math.sin(subPhase)>=0?1:-1):subShape==='TRIANGLE'?Math.asin(Math.sin(subPhase))*2/Math.PI:Math.sin(subPhase))*s.subLevel,rawNoise=this.random()*2-1,color=clamp(s.noiseColor??.5);this.noiseState+=((.01+color*.45)*(rawNoise-this.noiseState));const noise=lerp(this.noiseState,rawNoise,color)*(s.noiseKey?this.velocity:1)*s.noiseLevel,target=s.subDirect?'MASTER':'A';buses[target][0]+=sub;buses[target][1]+=sub;buses.A[0]+=noise;buses.A[1]+=noise;const fa=s.filterA||{},fb=s.filterB||{},a=this.filter(buses.A,(fa.cutoff??.18)+mods.cutA*.2,(fa.resonance??.2)+mods.resA*.35,'A',(fa.mix??1)+mods.mixA,fa.drive??0,fa.pan??.5),b=this.filter(buses.B,(fb.cutoff??.24)+mods.cutB*.2,(fb.resonance??.3)+mods.resB*.35,'B',(fb.mix??1)+mods.mixB,fb.drive??0,fb.pan??.5);let filtered;if(s.filterRouting==='SERIES A › B')filtered=this.filter(a,fb.cutoff??.24,fb.resonance??.3,'B',fb.mix??1,fb.drive??0,fb.pan??.5);else if(s.filterRouting==='SERIES B › A')filtered=this.filter(b,fa.cutoff??.18,fa.resonance??.2,'A',fa.mix??1,fa.drive??0,fa.pan??.5);else filtered=[(a[0]+b[0]),(a[1]+b[1])];return filtered.map((value,c)=>(value+buses.MASTER[c])*this.velocity*env)}
  release(){if(!this.released){this.releaseLevel=this.envelope();this.released=true;this.releaseAt=this.age}}
}
class NocturneProcessor extends AudioWorkletProcessor {
  constructor(){super();this.voices=[];this.fxPhase=0;this.blocks=0;this.wasm=null;this.delay=[new Float32Array(sampleRate),new Float32Array(sampleRate)];this.delayIndex=0;this.low=[0,0];this.settings={filterRouting:'PARALLEL',filterA:{cutoff:.18,resonance:.2,mix:.15},filterB:{cutoff:.24,resonance:.3,mix:.42},oscRoutes:['A','B','MASTER'],oscModes:['wavetable','wavetable','wavetable'],subLevel:.12,subShape:'SINE',subDirect:false,noiseLevel:.015,noiseColor:.5,noiseKey:false,macros:Array(8).fill(.5),fxParams:{},lfoRate:1.4,lfo2Rate:.65,env:{attack:.03,decay:.22,sustain:.68,release:.45},granular:{size:.42,density:.66,spray:.28,texture:.57},spectral:{blur:.36,shift:.51,formant:.63,stretch:.21},routes:[],fxModules:[],osc:[{position:.18,tune:0,level:.8,warp:.2},{position:.52,tune:0,level:.6,warp:.1},{position:.82,tune:-12,level:.44,warp:.1}]};this.port.onmessage=e=>this.message(e.data)}
  message(data){if(data.type==='noteOn'){const limit=this.settings.polyphony||16;while(this.voices.length>=limit){const released=this.voices.findIndex(v=>v.released);this.voices.splice(released<0?0:released,1)}this.voices.push(new NocturneVoice(data.note,data.velocity||.8,this.settings,sampleRate*(this.settings.oversampling||1)))}if(data.type==='noteOff')this.voices.forEach(v=>{if(v.note===data.note)v.release()});if(data.type==='panic')this.voices=[];if(data.type==='settings'){this.settings=data.settings;this.voices.forEach(v=>v.settings=data.settings)}if(data.type==='source')this.settings.source={...(this.settings.source||{}),...data.source};if(data.type==='wasm')WebAssembly.instantiate(data.bytes).then(result=>{this.wasm=result.instance.exports;this.port.postMessage({type:'wasmReady'})}).catch(()=>this.port.postMessage({type:'wasmError'}))}
  effects(stereo){const params=this.settings.fxParams||{},drive=clamp((params.DISTORTION?.drive??.68)+(this.settings.fxDriveMod||0),0,1),delayMix=params.DELAY?.mix??.42,reverbMix=params.REVERB?.mix??.42,chorusMix=params.CHORUS?.mix??.42,compressorMix=params.COMPRESSOR?.mix??.42,eqMix=params.EQ?.mix??.42,utilityMix=params.UTILITY?.mix??.42;for(const name of this.settings.fxModules||[]){this.fxPhase+=1/sampleRate;if(name==='FLANGER')stereo=stereo.map((x,c)=>x+read(this.delay[c],this.delayIndex-(120+Math.sin(this.fxPhase*3)*90))*(params.FLANGER?.mix??.34));if(name==='PHASER')stereo=stereo.map((x,c)=>{this.low[c]+=.08*(x-this.low[c]);return lerp(x,x-this.low[c]*.72,params.PHASER?.mix??.6)});if(name==='CONVOLUTION')stereo=stereo.map((x,c)=>x+read(this.delay[c],this.delayIndex-4200)*.28+read(this.delay[c],this.delayIndex-7800)*.16);if(name==='FILTER FX')stereo=stereo.map((x,c)=>{this.low[c]+=.12*(x-this.low[c]);return this.low[c]});if(name==='STEREO WIDTH'){const mid=(stereo[0]+stereo[1])*.5,side=(stereo[0]-stereo[1])*.68;stereo=[mid+side,mid-side]}if(name==='MID / SIDE')stereo=[stereo[0]*1.08,stereo[1]*.92];if(name==='MULTIBAND SPLIT')stereo=stereo.map(x=>Math.tanh(x*1.24));if(name==='MONO BASS'){const mid=(stereo[0]+stereo[1])*.5;stereo=[lerp(stereo[0],mid,utilityMix),lerp(stereo[1],mid,utilityMix)]}if(name==='CHORUS'||name==='HYPER DIMENSION')stereo=stereo.map((x,c)=>x+read(this.delay[c],this.delayIndex-(360+c*90+Math.sin(this.fxPhase*2.2)*120))*chorusMix*.76);if(name==='OTT')stereo=stereo.map(x=>lerp(x,Math.sign(x)*Math.pow(Math.abs(x),.72)*.82,compressorMix));if(name==='DISTORTION')stereo=stereo.map(x=>this.wasm?.soft_clip?this.wasm.soft_clip(x,1+drive*4):Math.tanh(x*(1+drive*4)));if(name==='DELAY')stereo=stereo.map((x,c)=>x+read(this.delay[c],this.delayIndex-Math.round(900+(params.DELAY?.time??.54)*9000))*delayMix*.68);if(name==='REVERB')stereo=stereo.map((x,c)=>x+(read(this.delay[c],this.delayIndex-9200)*.24+read(this.delay[c],this.delayIndex-14700)*.14)*reverbMix*2);if(name==='EQ')stereo=stereo.map((x,c)=>x+(x-this.low[c])*(eqMix-.5)*.56)}stereo.forEach((x,c)=>this.delay[c][this.delayIndex]=x);this.delayIndex=(this.delayIndex+1)%this.delay[0].length;return stereo}
  process(_,outputs){const started=Date.now(),out=outputs[0],oversampling=this.settings.oversampling||1;out.forEach(c=>c.fill(0));for(let i=0;i<out[0].length;i++){let stereo=[0,0];for(let sub=0;sub<oversampling;sub++){let partial=[0,0];this.voices=this.voices.filter(v=>{v.rate=sampleRate*oversampling;const next=v.next();if(next===null)return false;partial[0]+=next[0];partial[1]+=next[1];return true});stereo[0]+=partial[0]/oversampling;stereo[1]+=partial[1]/oversampling}this.settings.fxDriveMod=this.voices[0]?.modulations(0,0,0).drive||0;stereo=this.effects(stereo).map(x=>Math.tanh(x*1.45));out.forEach((channel,c)=>channel[i]=stereo[c]??stereo[0])}if(++this.blocks%24===0)this.port.postMessage({type:'cpu',value:clamp((Date.now()-started)/(128/sampleRate*1000))});return true}
}
registerProcessor('nocturne-synth',NocturneProcessor);
